import {
  mysqlTable,
  serial,
  varchar,
  text,
  timestamp,
  int,
  json,
} from "drizzle-orm/mysql-core";

export const prompts = mysqlTable("prompts", {
  id: serial("id").primaryKey(),
  title: varchar("title", { length: 255 }).notNull(),
  titleEn: varchar("title_en", { length: 255 }).notNull(),
  role: varchar("role", { length: 50 }).notNull(),
  tags: json("tags").notNull(),
  tagsEn: json("tags_en").notNull(),
  content: text("content").notNull(),
  description: text("description").notNull(),
  descriptionEn: text("description_en").notNull(),
  scenario: text("scenario").notNull(),
  scenarioEn: text("scenario_en").notNull(),
  problemFocus: text("problem_focus").notNull(),
  problemFocusEn: text("problem_focus_en").notNull(),
  author: varchar("author", { length: 100 }).notNull().default(""),
  likes: int("likes").notNull().default(0),
  views: varchar("views", { length: 20 }).notNull().default(""),
  comments: int("comments").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const skills = mysqlTable("skills", {
  id: serial("id").primaryKey(),
  title: varchar("title", { length: 255 }).notNull(),
  titleEn: varchar("title_en", { length: 255 }).notNull(),
  role: varchar("role", { length: 50 }).notNull(),
  tags: json("tags").notNull(),
  tagsEn: json("tags_en").notNull(),
  content: text("content").notNull(),
  description: text("description").notNull(),
  descriptionEn: text("description_en").notNull(),
  scenario: text("scenario").notNull(),
  scenarioEn: text("scenario_en").notNull(),
  problemFocus: text("problem_focus").notNull(),
  problemFocusEn: text("problem_focus_en").notNull(),
  author: varchar("author", { length: 100 }).notNull().default(""),
  likes: int("likes").notNull().default(0),
  views: varchar("views", { length: 20 }).notNull().default(""),
  comments: int("comments").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const workflows = mysqlTable("workflows", {
  id: serial("id").primaryKey(),
  title: varchar("title", { length: 255 }).notNull(),
  titleEn: varchar("title_en", { length: 255 }).notNull(),
  role: varchar("role", { length: 50 }).notNull(),
  tags: json("tags").notNull(),
  tagsEn: json("tags_en").notNull(),
  content: text("content").notNull(),
  description: text("description").notNull(),
  descriptionEn: text("description_en").notNull(),
  scenario: text("scenario").notNull(),
  scenarioEn: text("scenario_en").notNull(),
  problemFocus: text("problem_focus").notNull(),
  problemFocusEn: text("problem_focus_en").notNull(),
  steps: json("steps"),
  author: varchar("author", { length: 100 }).notNull().default(""),
  likes: int("likes").notNull().default(0),
  views: varchar("views", { length: 20 }).notNull().default(""),
  comments: int("comments").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
