import { getDb } from "../api/queries/connection";
import { skills } from "../db/schema";

async function importBatch() {
  const db = getDb();

  const batch = [
    // Google Stitch Skills (7)
    {
      title: "stitch-generate-designs: AI Design Generation",
      titleEn: "stitch-generate-designs: AI Design Generation",
      role: "creator",
      tags: ["Design System", "AI Design", "Google Stitch", "Claude Code", "AI Skill"],
      tagsEn: ["Design System", "AI Design", "Google Stitch", "Claude Code", "AI Skill"],
      content: "Google Stitch official skill. Generate high-fidelity UI designs from text descriptions. Supports multiple device sizes (phone/tablet/desktop), automatic design system application, and iterative modifications.\n\nInstall: npx skills add google/stitch-skills@generate-designs -g -y\nSource: https://github.com/google/stitch-skills",
      description: "Google Stitch: generate UI designs from text descriptions",
      descriptionEn: "Google Stitch: generate UI designs from text descriptions",
      scenario: "Designers and developers quickly generating UI prototypes",
      scenarioEn: "Designers and developers quickly generating UI prototypes",
      problemFocus: "Design mockup creation is time-consuming",
      problemFocusEn: "Design mockup creation is time-consuming",
      author: "Google · Stitch Skills", likes: 128, views: "9.5K", comments: 18,
    },
    {
      title: "stitch-image-to-design: Image to Design Conversion",
      titleEn: "stitch-image-to-design: Image to Design Conversion",
      role: "creator",
      tags: ["Design System", "Image to Design", "Google Stitch", "Claude Code", "AI Skill"],
      tagsEn: ["Design System", "Image to Design", "Google Stitch", "Claude Code", "AI Skill"],
      content: "Google Stitch official skill. Convert reference images or sketches into editable UI designs. Supports style extraction from reference images, sketch to high-fidelity conversion, screenshot to design restoration, and style migration.\n\nInstall: npx skills add google/stitch-skills@generate-designs-from-image -g -y\nSource: https://github.com/google/stitch-skills",
      description: "Convert reference images or sketches into editable UI designs",
      descriptionEn: "Convert reference images or sketches into editable UI designs",
      scenario: "Designers converting sketches to editable designs",
      scenarioEn: "Designers converting sketches to editable designs",
      problemFocus: "Sketch to high-fidelity conversion requires professional skills",
      problemFocusEn: "Sketch to high-fidelity conversion requires professional skills",
      author: "Google · Stitch Skills", likes: 115, views: "8.2K", comments: 15,
    },
    {
      title: "stitch-update-design: Design Iteration & Update",
      titleEn: "stitch-update-design: Design Iteration & Update",
      role: "creator",
      tags: ["Design System", "Design Iteration", "Google Stitch", "Claude Code", "AI Skill"],
      tagsEn: ["Design System", "Design Iteration", "Google Stitch", "Claude Code", "AI Skill"],
      content: "Google Stitch official skill. Iterate and update existing design mockups. Supports local modifications, global style updates, multi-version comparison, and change history tracking.\n\nInstall: npx skills add google/stitch-skills@update-design -g -y\nSource: https://github.com/google/stitch-skills",
      description: "Iterate and version-manage existing design mockups",
      descriptionEn: "Iterate and version-manage existing design mockups",
      scenario: "Designers iterating existing mockups quickly",
      scenarioEn: "Designers iterating existing mockups quickly",
      problemFocus: "Design modifications require manual adjustment of many elements",
      problemFocusEn: "Design modifications require manual adjustment of many elements",
      author: "Google · Stitch Skills", likes: 98, views: "7.1K", comments: 12,
    },
    {
      title: "stitch-design-system-extraction: Design System Extraction",
      titleEn: "stitch-design-system-extraction: Design System Extraction",
      role: "creator",
      tags: ["Design System", "Spec Extraction", "Google Stitch", "Claude Code", "AI Skill"],
      tagsEn: ["Design System", "Spec Extraction", "Google Stitch", "Claude Code", "AI Skill"],
      content: "Google Stitch official skill. Automatically extract design system specs from mockups: color palette, typography, spacing/layout rules, and component library generation.\n\nInstall: npx skills add google/stitch-skills@design-system-extraction -g -y\nSource: https://github.com/google/stitch-skills",
      description: "Extract colors, fonts, spacing from design mockups automatically",
      descriptionEn: "Extract colors, fonts, spacing from design mockups automatically",
      scenario: "Design teams extracting design system specs from mockups",
      scenarioEn: "Design teams extracting design system specs from mockups",
      problemFocus: "Design specs scattered across mockups, manual extraction is time-consuming",
      problemFocusEn: "Design specs scattered across mockups, manual extraction is time-consuming",
      author: "Google · Stitch Skills", likes: 106, views: "7.8K", comments: 14,
    },
    {
      title: "stitch-react-components: Design to React Components",
      titleEn: "stitch-react-components: Design to React Components",
      role: "developer",
      tags: ["Frontend", "React", "Design to Code", "Google Stitch", "AI Skill"],
      tagsEn: ["Frontend", "React", "Design to Code", "Google Stitch", "AI Skill"],
      content: "Google Stitch official skill. One-click converting design mockups to usable React component code. Generates CSS-in-JS styles, component props definitions, and responsive adaptations.\n\nInstall: npx skills add google/stitch-skills@react-components -g -y\nSource: https://github.com/google/stitch-skills",
      description: "One-click convert design mockups to React component code",
      descriptionEn: "One-click convert design mockups to React component code",
      scenario: "Frontend developers converting designs to React components",
      scenarioEn: "Frontend developers converting designs to React components",
      problemFocus: "Manual design-to-code conversion is time-consuming with pixel deviations",
      problemFocusEn: "Manual design-to-code conversion is time-consuming with pixel deviations",
      author: "Google · Stitch Skills", likes: 142, views: "10.5K", comments: 21,
    },
    {
      title: "stitch-prototype-video: Design Demo Video Generation",
      titleEn: "stitch-prototype-video: Design Demo Video Generation",
      role: "creator",
      tags: ["Design System", "Demo Video", "Google Stitch", "Claude Code", "AI Skill"],
      tagsEn: ["Design System", "Demo Video", "Google Stitch", "Claude Code", "AI Skill"],
      content: "Google Stitch official skill. Convert UI design mockups into interactive demo videos. Supports interactive demos, click flow recording, animation generation, and video export.\n\nInstall: npx skills add google/stitch-skills@design-prototype-video -g -y\nSource: https://github.com/google/stitch-skills",
      description: "Convert UI designs into interactive demo videos",
      descriptionEn: "Convert UI designs into interactive demo videos",
      scenario: "Designers and PMs creating demo videos from mockups",
      scenarioEn: "Designers and PMs creating demo videos from mockups",
      problemFocus: "Design demos require manual recording and editing",
      problemFocusEn: "Design demos require manual recording and editing",
      author: "Google · Stitch Skills", likes: 89, views: "6.5K", comments: 11,
    },
    {
      title: "stitch-design: Google Stitch Design Assistant",
      titleEn: "stitch-design: Google Stitch Design Assistant",
      role: "creator",
      tags: ["Design System", "AI Design Assistant", "Google Stitch", "Claude Code", "AI Skill"],
      tagsEn: ["Design System", "AI Design Assistant", "Google Stitch", "Claude Code", "AI Skill"],
      content: "Google Stitch core design assistant skill. Manages design systems and component libraries. Supports design system management, component library maintenance, design spec checking, and cross-skill coordination.\n\nInstall: npx skills add google/stitch-skills@design -g -y\nSource: https://github.com/google/stitch-skills",
      description: "Core design assistant managing design systems and component libraries",
      descriptionEn: "Core design assistant managing design systems and component libraries",
      scenario: "Design teams managing design systems uniformly",
      scenarioEn: "Design teams managing design systems uniformly",
      problemFocus: "Design system maintenance is difficult, component versions are chaotic",
      problemFocusEn: "Design system maintenance is difficult, component versions are chaotic",
      author: "Google · Stitch Skills", likes: 118, views: "8.6K", comments: 16,
    },
    // Single skills
    {
      title: "markdown-viewer: Markdown Code Block Visualization",
      titleEn: "markdown-viewer: Markdown Code Block Visualization",
      role: "developer",
      tags: ["Markdown", "Code Visualization", "Documentation", "Claude Code", "AI Skill"],
      tagsEn: ["Markdown", "Code Visualization", "Documentation", "Claude Code", "AI Skill"],
      content: "Skill that brings Markdown code blocks to life. Not just syntax highlighting, but making code visualizable and runnable in documents. Supports enhanced syntax highlighting, real-time code preview, chart and diagram rendering (Mermaid), and interactive code demos.\n\nSource: https://github.com/markdown-viewer/skills",
      description: "Make Markdown code blocks alive with real-time preview",
      descriptionEn: "Make Markdown code blocks alive with real-time preview",
      scenario: "Technical documentation and code tutorials needing visual code display",
      scenarioEn: "Technical documentation and code tutorials needing visual code display",
      problemFocus: "Markdown code blocks are static text, cannot show execution effects",
      problemFocusEn: "Markdown code blocks are static text, cannot show execution effects",
      author: "markdown-viewer · Daily Skills", likes: 76, views: "5.4K", comments: 9,
    },
    {
      title: "claude-task-master: Task Management (Andrej Karpathy)",
      titleEn: "claude-task-master: Task Management (Andrej Karpathy)",
      role: "developer",
      tags: ["Claude Code", "Task Management", "Andrej Karpathy", "AI Skill"],
      tagsEn: ["Claude Code", "Task Management", "Andrej Karpathy", "AI Skill"],
      content: "Recommended by Tesla former AI Director Andrej Karpathy. Breaks complex projects into manageable tasks with deep Claude Code integration. Supports multi-level task nesting, automatic task description and acceptance criteria generation, auto-archiving on completion, and team collaboration.\n\nSource: https://github.com/eyaltoledano/claude-task-master",
      description: "Andrej Karpathy-recommended task management with deep Claude Code integration",
      descriptionEn: "Andrej Karpathy-recommended task management with deep Claude Code integration",
      scenario: "Developers managing complex projects with many tasks and dependencies",
      scenarioEn: "Developers managing complex projects with many tasks and dependencies",
      problemFocus: "Complex project task management is chaotic, priorities unclear",
      problemFocusEn: "Complex project task management is chaotic, priorities unclear",
      author: "eyaltoledano · Andrej Karpathy", likes: 156, views: "12.3K", comments: 24,
    },
    {
      title: "planning-with-files: File-Based Intelligent Planning",
      titleEn: "planning-with-files: File-Based Intelligent Planning",
      role: "developer",
      tags: ["Claude Code", "File Management", "Intelligent Planning", "AI Skill"],
      tagsEn: ["Claude Code", "File Management", "Intelligent Planning", "AI Skill"],
      content: "File-based intelligent planning skill. AI analyzes project file structure and code content to auto-generate development plans and task lists. Capabilities include: codebase structure analysis, automatic task generation, development plan creation, file dependency mapping, and code complexity assessment.\n\nSource: https://github.com/anthropics/skills/tree/main/planning-with-files",
      description: "Analyze codebase structure to auto-generate development plans",
      descriptionEn: "Analyze codebase structure to auto-generate development plans",
      scenario: "Developers taking over new projects needing quick understanding",
      scenarioEn: "Developers taking over new projects needing quick understanding",
      problemFocus: "High understanding cost when taking over new projects",
      problemFocusEn: "High understanding cost when taking over new projects",
      author: "anthropics · GitHub Skills", likes: 92, views: "6.8K", comments: 13,
    },
  ];

  for (const s of batch) {
    await db.insert(skills).values(s);
  }
  console.log(`Inserted ${batch.length} skills (batch 3b)`);
  process.exit(0);
}

importBatch().catch(console.error);
