import { getDb } from "../api/queries/connection";
import { prompts, skills } from "../db/schema";

async function importWechatContent() {
  const db = getDb();
  console.log("Importing WeChat article content...");

  // ===== Skills from Article 1: PPT AI Skills (4 skills) =====
  const pptSkills = [
    {
      title: "huashu-design：设计原型级PPT生成",
      titleEn: "huashu-design: Design Prototype PPT Generation",
      role: "creator",
      tags: ["PPT生成", "设计原型", "AI技能", "Claude Code"],
      tagsEn: ["PPT Generation", "Design Prototype", "AI Skill", "Claude Code"],
      content: `## huashu-design Skill 使用指南\n\n### 核心定位\n设计原型级PPT生成工具，专注于将设计稿快速转化为可演示的HTML幻灯片。\n\n### 工作流程\n1. 提供设计稿或参考网站的截图\n2. Skill会自动分析设计元素：配色、排版、字体、间距\n3. 生成HTML格式的PPT，横向翻页，浏览器直接打开\n4. 支持自定义主题和动画效果\n\n### 适用场景\n- 需要快速产出设计原型的产品评审\n- 设计师与开发者的沟通桥梁\n- 高保真概念验证\n\n### 安装\n\`\`\`bash\nnpx skills add alchaincyf/huashu-skills@huashu-design -g -y\n\`\`\`\n\n### 追踪来源\nGitHub: https://github.com/alchaincyf/huashu-skills`,
      description: "将设计稿转化为可演示HTML幻灯片的AI技能，支持自动分析配色、排版、字体等设计元素",
      descriptionEn: "AI skill that transforms design mockups into presentable HTML slides, auto-analyzing color, typography, and layout",
      scenario: "设计师需要快速将设计概念转化为可交互的演示原型，用于产品评审或客户展示",
      scenarioEn: "Designers needing to quickly turn design concepts into interactive prototypes for reviews or client presentations",
      problemFocus: "设计稿到PPT的转换耗时且容易失真，传统方式需要手动截图和排版",
      problemFocusEn: "Converting design mockups to PPT is time-consuming and prone to distortion, requiring manual screenshots and layout",
      author: "huashu-skills · 老严评测",
      likes: 68, views: "4.2K", comments: 9,
    },
    {
      title: "ppt-master：商务PPT专业生成",
      titleEn: "ppt-master: Professional Business PPT Generation",
      role: "creator",
      tags: ["PPT生成", "商务演示", "AI技能", "Claude Code"],
      tagsEn: ["PPT Generation", "Business Presentation", "AI Skill", "Claude Code"],
      content: `## ppt-master Skill 使用指南\n\n### 核心定位\n面向商务场景的专业PPT生成工具，产出高质量、结构化的演示文稿。\n\n### 工作流程\n1. 输入主题和大纲\n2. Skill会自动生成完整的PPT结构：封面、目录、内容页、总结页\n3. 支持多种商务模板：汇报型、提案型、培训型\n4. 输出为HTML或PPTX格式\n\n### 特色功能\n- 自动图表生成（柱状图、饼图、折线图）\n- 数据可视化建议\n- 商务配色方案\n- 演讲者备注自动生成\n\n### 安装\n\`\`\`bash\nnpx skills add hugohe3/ppt-master@ppt-master -g -y\n\`\`\`\n\n### 追踪来源\nGitHub: https://github.com/hugohe3/ppt-master`,
      description: "面向商务场景的专业PPT生成AI技能，支持自动图表、数据可视化和演讲者备注",
      descriptionEn: "Professional business PPT generation AI skill with auto charts, data visualization, and speaker notes",
      scenario: "商务人士需要快速制作高质量的工作汇报、项目提案或培训材料",
      scenarioEn: "Business professionals needing to quickly create high-quality reports, proposals, or training materials",
      problemFocus: "商务PPT制作耗时，图表设计不专业，演讲准备不充分",
      problemFocusEn: "Business PPT creation is time-consuming, charts look unprofessional, speech preparation is inadequate",
      author: "ppt-master · 老严评测",
      likes: 72, views: "4.8K", comments: 11,
    },
    {
      title: "guizang-ppt-skill：技术分享PPT神器",
      titleEn: "guizang-ppt-skill: Technical Presentation PPT Tool",
      role: "developer",
      tags: ["PPT生成", "技术分享", "WebGL", "单文件HTML", "AI技能"],
      tagsEn: ["PPT Generation", "Tech Presentation", "WebGL", "Single File HTML", "AI Skill"],
      content: `## guizang-ppt-skill 使用指南\n\n### 核心定位\n单文件HTML技术分享PPT生成，横向翻页，浏览器直接打开运行。\n\n### 核心亮点：WebGL流体背景\n不是廉价渐变动画，而是有真实质感的流体效果。hero页一打开像在看Apple发布会。\n\n### 配色预设（5套，不支持自定义）\n- 墨水经典\n- 靛蓝瓷\n- 森林墨\n- 牛皮纸\n- 沙丘\n\n### 技术特点\n- 单文件HTML，完全独立运行\n- 不需要安装任何东西\n- 浏览器打开即可\n- WebGL硬件加速\n\n### 安装\n\`\`\`bash\nnpx skills add op7418/guizang-ppt-skill@guizang-ppt -g -y\n\`\`\`\n\n### 追踪来源\nGitHub: https://github.com/op7418/guizang-ppt-skill`,
      description: "单文件HTML技术分享PPT生成工具，WebGL流体背景效果惊艳，5套预设配色",
      descriptionEn: "Single-file HTML tech presentation PPT tool with stunning WebGL fluid backgrounds and 5 preset color schemes",
      scenario: "技术人员需要做技术分享、内部分享或开源项目演示",
      scenarioEn: "Technical professionals needing to create tech talks, internal sharing sessions, or open-source project demos",
      problemFocus: "技术PPT要么太简陋要么制作耗时，没有适合技术人员的专用工具",
      problemFocusEn: "Tech presentations are either too basic or time-consuming to create, lacking tools designed for technical professionals",
      author: "guizang-ppt-skill · 老严评测",
      likes: 95, views: "8.1K", comments: 18,
    },
    {
      title: "Kami：专业文档型PPT",
      titleEn: "Kami: Professional Document-Style PPT",
      role: "creator",
      tags: ["PPT生成", "专业文档", "AI技能", "Claude Code"],
      tagsEn: ["PPT Generation", "Professional Document", "AI Skill", "Claude Code"],
      content: `## Kami Skill 使用指南\n\n### 核心定位\n面向专业文档和学术场景的PPT生成工具，强调内容结构和逻辑表达。\n\n### 工作流程\n1. 输入文档内容或研究论文\n2. Skill会自动提取关键论点、数据和结论\n3. 生成结构清晰、逻辑严密的PPT\n4. 支持LaTeX公式和代码高亮\n\n### 适用场景\n- 学术论文答辩\n- 技术白皮书展示\n- 产品需求文档评审\n- 研究报告汇报\n\n### 安装\n\`\`\`bash\nnpx skills add tw93/Kami@kami -g -y\n\`\`\`\n\n### 追踪来源\nGitHub: https://github.com/tw93/Kami`,
      description: "面向专业文档和学术场景的PPT生成AI技能，支持LaTeX公式和代码高亮",
      descriptionEn: "Professional document and academic PPT generation AI skill, supporting LaTeX formulas and code highlighting",
      scenario: "学术研究者、产品经理需要制作专业文档和学术PPT",
      scenarioEn: "Researchers and PMs needing to create professional documents and academic presentations",
      problemFocus: "学术论文PPT制作繁琐，公式排版困难，代码展示不美观",
      problemFocusEn: "Academic PPT creation is tedious, formula formatting is difficult, code display is unattractive",
      author: "Kami · 老严评测",
      likes: 54, views: "3.6K", comments: 7,
    },
  ];

  // ===== Skills from Article 2: Claude Code 10 Skills (8 new after dedup) =====
  const claudeSkills = [
    {
      title: "find-skills：Claude Code技能搜索引擎",
      titleEn: "find-skills: Claude Code Skill Search Engine",
      role: "developer",
      tags: ["Claude Code", "技能发现", "效率工具", "AI技能"],
      tagsEn: ["Claude Code", "Skill Discovery", "Productivity", "AI Skill"],
      content: `## find-skills 使用指南\n\n### 核心定位\nClaude Code生态里的技能搜索入口。帮你从skills生态里找到现成方案。\n\n### 解决的问题\n- 这个事到底有没有现成skill？\n- 我要不要自己写？\n- 有没有别人已经沉淀好的流程？\n- 这个方向是不是已经有成熟模板？\n\n### 核心价值\n降低探索生态的成本。理解成"技能层的搜索引擎"。\n\n### 安装\n\`\`\`bash\nnpx skills add vercel-labs/skills@find-skills -g -y\n\`\`\`\n\n### 追踪来源\nhttps://skills.sh/vercel-labs/skills/find-skills`,
      description: "Claude Code生态的技能搜索引擎，帮你发现现成可用的skills而不是重复造轮子",
      descriptionEn: "Claude Code ecosystem skill search engine, helping you discover existing skills instead of reinventing wheels",
      scenario: "Claude Code用户不知道有哪些可用技能，浪费时间重复摸索",
      scenarioEn: "Claude Code users don't know what skills are available, wasting time on repeated exploration",
      problemFocus: "使用AI工具最浪费时间的不是执行，而是重复摸索：这个事到底有没有现成skill？",
      problemFocusEn: "The most time-wasting part of using AI tools isn't execution, it's repeated exploration: does a skill already exist for this?",
      author: "vercel-labs · Import AI推荐",
      likes: 88, views: "5.2K", comments: 12,
    },
    {
      title: "skill-creator：把经验固化为可复用Skill",
      titleEn: "skill-creator: Turn Experience into Reusable Skills",
      role: "developer",
      tags: ["Claude Code", "技能创建", "工作流固化", "AI技能"],
      tagsEn: ["Claude Code", "Skill Creation", "Workflow固化", "AI Skill"],
      content: `## skill-creator 使用指南\n\n### 核心定位\n如果某个动作一周会重复很多次，那它就值得被固化。skill-creator把重复动作从"零散经验"变成"可复用流程"。\n\n### 工作方式\n1. 描述你经常重复的工作流程\n2. skill-creator帮你将其转化为结构化Skill\n3. 生成的Skill可以被Claude Code反复调用\n4. 随着使用不断迭代优化\n\n### 核心价值\n当Claude Code开始复用你的workflow，它就不再只是助手，而更像一个逐渐熟悉你做事方式的同事。\n\n### 安装\n\`\`\`bash\nnpx skills add anthropics/skills@skill-creator -g -y\n\`\`\`\n\n### 追踪来源\nhttps://skills.sh/anthropics/skills/skill-creator`,
      description: "将重复性工作流程固化为可复用AI技能的创建工具，让Claude Code逐渐熟悉你的做事方式",
      descriptionEn: "Tool for turning repetitive workflows into reusable AI skills, letting Claude Code learn your working style",
      scenario: "需要把高频重复的工作流程自动化，减少每次从零开始配置的时间",
      scenarioEn: "Needing to automate high-frequency repetitive workflows, reducing setup time from scratch each time",
      problemFocus: "同样操作每周重复多次，每次都从零开始写prompt效率极低",
      problemFocusEn: "Repeating the same operations weekly, writing prompts from scratch each time is extremely inefficient",
      author: "anthropics · Import AI推荐",
      likes: 112, views: "7.5K", comments: 19,
    },
    {
      title: "tmux：终端会话持久化管理",
      titleEn: "tmux: Terminal Session Persistence Management",
      role: "developer",
      tags: ["Claude Code", "终端管理", "tmux", "远程开发", "AI技能"],
      tagsEn: ["Claude Code", "Terminal Management", "tmux", "Remote Development", "AI Skill"],
      content: `## tmux Skill 使用指南\n\n### 核心定位\nClaude Code的终端会话持久化管理工具。解决命令跑很久、过程要持续观察、多个任务并行等场景。\n\n### 解决的问题\n- 命令要跑很久，不能断开\n- 过程要持续观察日志\n- 中途要交互输入\n- 多个任务要并行\n- 远端环境不能轻易断开\n\n### 核心价值\n让Claude Code不只是"执行一次"，而是可以持续控制一个已存在的终端环境。\n\n### 安装\n\`\`\`bash\nnpx skills add steipete/clawdis@tmux -g -y\n\`\`\`\n\n### 追踪来源\nhttps://skills.sh/steipete/clawdis/tmux`,
      description: "Claude Code终端会话持久化管理skill，支持长时间任务、日志监控和多任务并行",
      descriptionEn: "Claude Code terminal session persistence skill, supporting long-running tasks, log monitoring, and multi-task parallelism",
      scenario: "开发运维人员需要管理长时间运行的任务和远程会话",
      scenarioEn: "DevOps professionals needing to manage long-running tasks and remote sessions",
      problemFocus: "Claude Code执行长时间任务时会话断开，无法持续监控和交互",
      problemFocusEn: "Claude Code loses session when executing long-running tasks, unable to monitor and interact continuously",
      author: "steipete · Import AI推荐",
      likes: 76, views: "4.8K", comments: 11,
    },
    {
      title: "webapp-testing：自动化测试工程化",
      titleEn: "webapp-testing: Automated Testing Engineering",
      role: "developer",
      tags: ["Claude Code", "自动化测试", "Playwright", "E2E测试", "AI技能"],
      tagsEn: ["Claude Code", "Automated Testing", "Playwright", "E2E Testing", "AI Skill"],
      content: `## webapp-testing Skill 使用指南\n\n### 核心定位\n给Claude Code加了一层测试工程经验。让它写的测试不只是"能写出来"，而是"写得稳定、清晰、可维护"。\n\n### 提升领域\n- 测试结构怎么组织\n- 断言怎么写更有意义\n- 边界条件怎么覆盖\n- Playwright用例怎么更像真实场景\n- 哪些测试值得保留，哪些只是噪音\n\n### 安装\n\`\`\`bash\nnpx skills add anthropics/skills@webapp-testing -g -y\n\`\`\`\n\n### 追踪来源\nhttps://skills.sh/anthropics/skills/webapp-testing`,
      description: "给Claude Code增加测试工程经验的skill，提升测试结构、断言质量和Playwright用例真实性",
      descriptionEn: "Adds testing engineering experience to Claude Code, improving test structure, assertion quality, and Playwright case realism",
      scenario: "前端开发者需要编写稳定可维护的自动化测试，特别是E2E测试",
      scenarioEn: "Frontend developers needing to write stable, maintainable automated tests, especially E2E tests",
      problemFocus: "AI生成的测试用例不稳定、不清晰、难以维护，缺乏测试工程最佳实践",
      problemFocusEn: "AI-generated test cases are unstable, unclear, and hard to maintain, lacking testing engineering best practices",
      author: "anthropics · Import AI推荐",
      likes: 82, views: "5.1K", comments: 13,
    },
    {
      title: "api-docs：技术文档工程化生成",
      titleEn: "api-docs: Technical Documentation Engineering",
      role: "developer",
      tags: ["Claude Code", "技术文档", "API文档", "README", "AI技能"],
      tagsEn: ["Claude Code", "Technical Documentation", "API Docs", "README", "AI Skill"],
      content: `## api-docs Skill 使用指南\n\n### 核心定位\n给Claude Code一套文档组织框架，让它从"会堆字"变成"靠谱的技术写作者"。\n\n### 核心价值\nClaude Code很擅长理解代码和结构，但如果没有约束，写出来的文档容易"看着完整，实际上没重点"。\n\n### 适用场景\n- 补README\n- 整理API文档\n- 给项目写上手说明\n- 技术博客撰写\n\n### 安装\n\`\`\`bash\nnpx skills add vercel-labs/skills@api-docs -g -y\n\`\`\`\n\n### 追踪来源\nhttps://skills.sh/vercel-labs/skills/api-docs`,
      description: "给Claude Code技术文档组织框架的skill，让文档写作从堆字变为工程化输出",
      descriptionEn: "Provides Claude Code with a technical documentation framework, turning doc writing from word-stacking to engineering output",
      scenario: "开发者需要为项目编写高质量README、API文档和上手说明",
      scenarioEn: "Developers needing to write high-quality READMEs, API docs, and onboarding guides for projects",
      problemFocus: "AI生成的文档看起来完整但缺乏重点，没有工程化的文档结构",
      problemFocusEn: "AI-generated docs look complete but lack focus, without engineering-grade document structure",
      author: "vercel-labs · Import AI推荐",
      likes: 65, views: "4.2K", comments: 9,
    },
    {
      title: "git-refactor：Git操作与代码重构助手",
      titleEn: "git-refactor: Git Operations & Code Refactoring Assistant",
      role: "developer",
      tags: ["Claude Code", "Git", "代码重构", "版本控制", "AI技能"],
      tagsEn: ["Claude Code", "Git", "Code Refactoring", "Version Control", "AI Skill"],
      content: `## git-refactor Skill 使用指南\n\n### 核心定位\n把Claude Code从"会写代码"推向"能承担完整工作流"，覆盖Git操作和代码重构场景。\n\n### 能力范围\n- 智能commit message生成\n- 分支策略建议\n- 代码重构规划\n- 重构安全评估\n- Git历史清理\n\n### 安装\n\`\`\`bash\nnpx skills add vercel-labs/skills@git-refactor -g -y\n\`\`\``,
      description: "覆盖Git操作和代码重构场景的Claude Code skill，支持智能commit和重构安全评估",
      descriptionEn: "Claude Code skill covering Git operations and code refactoring, supporting smart commits and refactoring safety assessment",
      scenario: "开发者需要在重构代码时保持Git历史整洁和代码库健康",
      scenarioEn: "Developers needing to maintain clean Git history and codebase health during refactoring",
      problemFocus: "重构时容易破坏Git历史，commit message质量差，缺乏重构规划",
      problemFocusEn: "Refactoring easily breaks Git history, poor commit messages, lack of refactoring planning",
      author: "vercel-labs · Import AI推荐",
      likes: 71, views: "4.5K", comments: 10,
    },
    {
      title: "mcp-tools：MCP协议工具集成",
      titleEn: "mcp-tools: MCP Protocol Tool Integration",
      role: "developer",
      tags: ["Claude Code", "MCP", "工具集成", "协议", "AI技能"],
      tagsEn: ["Claude Code", "MCP", "Tool Integration", "Protocol", "AI Skill"],
      content: `## mcp-tools Skill 使用指南\n\n### 核心定位\nMCP(Model Context Protocol)工具集成skill，让Claude Code能够连接外部工具和数据源。\n\n### 能力范围\n- 连接外部API和数据源\n- 文件系统操作\n- 数据库查询\n- 第三方服务集成\n\n### 核心价值\nMCP是Claude Code扩展能力的协议层。通过mcp-tools，Claude Code可以从"会回答"变成"会做事"。\n\n### 安装\n\`\`\`bash\nnpx skills add vercel-labs/skills@mcp-tools -g -y\n\`\`\``,
      description: "MCP协议工具集成skill，让Claude Code连接外部API、数据源和第三方服务",
      descriptionEn: "MCP protocol tool integration skill, enabling Claude Code to connect to external APIs, data sources, and third-party services",
      scenario: "需要让Claude Code与外部工具和数据源交互的开发者",
      scenarioEn: "Developers needing Claude Code to interact with external tools and data sources",
      problemFocus: "Claude Code缺乏与外部世界交互的能力，只能处理本地代码和文本",
      problemFocusEn: "Claude Code lacks the ability to interact with the external world, only handling local code and text",
      author: "vercel-labs · Import AI推荐",
      likes: 58, views: "3.8K", comments: 8,
    },
  ];

  // ===== Skills from Article 3: OSS-Skill =====
  const ossSkills = [
    {
      title: "oss-skill：蒸馏开源项目的工程直觉",
      titleEn: "oss-skill: Distill Engineering Intuition from Open Source",
      role: "developer",
      tags: ["开源", "Vibe Coding", "工程判断", "Skill创建", "AI技能"],
      tagsEn: ["Open Source", "Vibe Coding", "Engineering Judgment", "Skill Creation", "AI Skill"],
      content: `## oss-skill 使用指南\n\n### 核心定位\n为开发者在Vibe Coding时提供的一套专业Playbook。关注开源作者、开源仓库在真实工程里的判断方式。\n\n### 灵感来源\n借鉴自女娲Skill(nuwa-skill, 1.2万+Star)。但关注点不同：nuwa-skill偏向人的思维框架，oss-skill偏向软件工程里具体的判断动作。\n\n### 工作流程\n1. **指定目标**：选择要蒸馏的开源项目或作者\n2. **六维度调研**：架构、变更、评审、文档、决策、演化\n3. **提炼落地内容**：工程判断维度、决策启发式、代码特征、开发任务映射\n4. **明确边界**：证据来自代码仓库就不外推到整个人\n\n### 追踪来源\nGitHub: https://github.com/lianchi/oss-skill\n灵感来源: https://github.com/alchaincyf/nuwa-skill`,
      description: "蒸馏开源项目的工程判断和决策模式，为Vibe Coding提供可复用的专业Playbook",
      descriptionEn: "Distills engineering judgment and decision patterns from open source projects, providing reusable professional playbooks for Vibe Coding",
      scenario: "开发者在AI写代码时需要工程判断力辅助，避免盲目信任AI输出",
      scenarioEn: "Developers needing engineering judgment assistance when AI writes code, avoiding blindly trusting AI output",
      problemFocus: "AI写代码效率高但缺乏工程判断，容易做出不合理的设计决策",
      problemFocusEn: "AI codes efficiently but lacks engineering judgment, easily making unreasonable design decisions",
      author: "lianchi · 炼赤开源",
      likes: 134, views: "9.8K", comments: 22,
    },
  ];

  // ===== Skills from Article 4: 5 Skills for Academic Paper (8 skills) =====
  const academicSkills = [
    {
      title: "research-proposal：Nature Reviews风格研究提案",
      titleEn: "research-proposal: Nature Reviews Style Research Proposal",
      role: "researcher",
      tags: ["学术研究", "研究提案", "Nature风格", "论文写作", "AI技能"],
      tagsEn: ["Academic Research", "Research Proposal", "Nature Style", "Paper Writing", "AI Skill"],
      content: `## research-proposal Skill 使用指南\n\n### 核心定位\nNature Reviews风格的研究提案生成，含40+参考文献占位。仓库426★。\n\n### 使用场景\n- 立项/开题阶段\n- 研究提案撰写\n- 基金申请书\n- 合作方案\n\n### 追踪来源\nGitHub: https://github.com/luwill/research-skills`,
      description: "Nature Reviews风格的研究提案生成skill，含40+参考文献占位，适合立项开题",
      descriptionEn: "Nature Reviews style research proposal generation skill with 40+ reference placeholders, suitable for project initiation",
      scenario: "学术研究者需要撰写高质量的研究提案和基金申请书",
      scenarioEn: "Academic researchers needing to write high-quality research proposals and grant applications",
      problemFocus: "研究提案格式不规范，参考文献管理混乱，立项成功率低",
      problemFocusEn: "Research proposal formatting is non-standard, reference management is chaotic, approval rate is low",
      author: "luwill · 学术废物收容所推荐",
      likes: 89, views: "6.2K", comments: 14,
    },
    {
      title: "paper-strategist：论文架构规划与评审节点",
      titleEn: "paper-strategist: Paper Architecture Planning & Review Nodes",
      role: "researcher",
      tags: ["学术研究", "论文规划", "评审节点", "论文写作", "AI技能"],
      tagsEn: ["Academic Research", "Paper Planning", "Review Nodes", "Paper Writing", "AI Skill"],
      content: `## paper-strategist Skill 使用指南\n\n### 核心定位\n拆出7个评审节点，提示要补的证据位。当前172★。\n\n### 工作流程\n1. 输入论文主题和初步思路\n2. Skill拆解出7个关键评审节点\n3. 每个节点提示需要补充的证据\n4. 生成完整的论文架构规划\n\n### 核心价值\n在写作前就预判审稿人可能提出的问题，提前准备好证据链。\n\n### 追踪来源\nGitHub: https://github.com/lishix520/academic-paper-skills`,
      description: "论文架构规划skill，拆解7个评审节点并提示需要补充的证据位",
      descriptionEn: "Paper architecture planning skill, breaking down 7 review nodes and prompting for evidence gaps",
      scenario: "学术写作者需要在投稿前预判审稿意见，完善论文架构",
      scenarioEn: "Academic writers needing to anticipate reviewer comments and refine paper structure before submission",
      problemFocus: "论文结构不清晰，审稿意见频出，投稿成功率低",
      problemFocusEn: "Unclear paper structure, frequent reviewer comments, low acceptance rates",
      author: "lishix520 · 学术废物收容所推荐",
      likes: 67, views: "4.5K", comments: 9,
    },
    {
      title: "paper-composer：学术论文正文骨架生成",
      titleEn: "paper-composer: Academic Paper Body Skeleton Generation",
      role: "researcher",
      tags: ["学术研究", "论文写作", "正文生成", "AI技能"],
      tagsEn: ["Academic Research", "Paper Writing", "Body Generation", "AI Skill"],
      content: `## paper-composer Skill 使用指南\n\n### 核心定位\n出骨架的学术论文写作skill。与scientific-writer配合：composer出骨架，scientific-writer负责润色。\n\n### 工作流程\n1. 输入研究数据和初步结论\n2. 生成论文正文骨架（Introduction→Methods→Results→Discussion）\n3. 自动插入数据占位和图表建议\n4. 与scientific-writer配合润色\n\n### 追踪来源\nGitHub: https://github.com/lishix520/academic-paper-skills`,
      description: "学术论文正文骨架生成skill，负责搭建Introduction到Discussion的完整框架",
      descriptionEn: "Academic paper body skeleton generation skill, building complete framework from Introduction to Discussion",
      scenario: "学术写作者需要快速搭建论文框架，确保结构完整",
      scenarioEn: "Academic writers needing to quickly scaffold paper structure ensuring completeness",
      problemFocus: "论文结构不完整，各部分逻辑连接薄弱，写作效率低",
      problemFocusEn: "Incomplete paper structure, weak logical connections between sections, low writing efficiency",
      author: "lishix520 · 学术废物收容所推荐",
      likes: 72, views: "4.8K", comments: 10,
    },
    {
      title: "scientific-writer：科学写作润色专家",
      titleEn: "scientific-writer: Scientific Writing Polish Expert",
      role: "researcher",
      tags: ["学术研究", "科学写作", "论文润色", "AI技能"],
      tagsEn: ["Academic Research", "Scientific Writing", "Paper Polish", "AI Skill"],
      content: `## scientific-writer Skill 使用指南\n\n### 核心定位\n负责论文润色的科学写作skill。主仓库1.7万★。与paper-composer配合。\n\n### 能力范围\n- 学术语言润色\n- 逻辑连贯性检查\n- 引用格式规范\n- 图表描述优化\n- 投稿信撰写\n\n### 追踪来源\nGitHub: https://github.com/K-Dense-AI/claude-scientific-writer`,
      description: "科学写作润色专家skill，1.7万★，负责学术语言优化和逻辑连贯性",
      descriptionEn: "Scientific writing polish expert skill, 17K stars, responsible for academic language optimization and logical coherence",
      scenario: "学术写作者需要提升论文语言质量和学术规范性",
      scenarioEn: "Academic writers needing to improve paper language quality and academic standards",
      problemFocus: "非母语写作者学术英语不规范，论文被拒稿率高",
      problemFocusEn: "Non-native writers struggle with academic English norms, high rejection rates",
      author: "K-Dense-AI · 学术废物收容所推荐",
      likes: 156, views: "12.3K", comments: 28,
    },
    {
      title: "statistical-analysis：统计分析与数据检验",
      titleEn: "statistical-analysis: Statistical Analysis & Data Testing",
      role: "dataScientist",
      tags: ["学术研究", "统计分析", "pandas", "statsmodels", "AI技能"],
      tagsEn: ["Academic Research", "Statistical Analysis", "pandas", "statsmodels", "AI Skill"],
      content: `## statistical-analysis Skill 使用指南\n\n### 核心定位\n自带pandas + statsmodels工作流的统计分析skill。\n\n### 能力范围\n- 描述性统计分析\n- 假设检验\n- 回归分析\n- 数据可视化\n- 显著性检验\n\n### 追踪来源\nGitHub: https://github.com/K-Dense-AI/claude-scientific-skills`,
      description: "自带pandas+statsmodels工作流的统计分析skill，覆盖假设检验到回归分析",
      descriptionEn: "Statistical analysis skill with built-in pandas+statsmodels workflow, covering hypothesis testing to regression analysis",
      scenario: "研究者需要进行统计分析和显著性检验",
      scenarioEn: "Researchers needing to perform statistical analysis and significance testing",
      problemFocus: "统计分析代码重复编写，检验方法选择困难，结果解释不准确",
      problemFocusEn: "Repeated statistical code writing, difficulty choosing test methods, inaccurate result interpretation",
      author: "K-Dense-AI · 学术废物收容所推荐",
      likes: 94, views: "7.1K", comments: 16,
    },
    {
      title: "latex-document：LaTeX期刊版式排版",
      titleEn: "latex-document: LaTeX Journal Typesetting",
      role: "researcher",
      tags: ["学术研究", "LaTeX", "期刊排版", "论文写作", "AI技能"],
      tagsEn: ["Academic Research", "LaTeX", "Journal Typesetting", "Paper Writing", "AI Skill"],
      content: `## latex-document Skill 使用指南\n\n### 核心定位\n负责期刊版式的LaTeX排版skill。\n\n### 工作流程\n1. 按README运行setup.sh\n2. 再执行scripts/compile_latex.sh\n\n### 追踪来源\nGitHub: https://github.com/ndpvt-web/latex-document-skill`,
      description: "LaTeX期刊版式排版skill，一键运行setup.sh和compile脚本生成期刊格式论文",
      descriptionEn: "LaTeX journal typesetting skill, one-click setup.sh and compile script to generate journal-formatted papers",
      scenario: "学术研究者需要制作符合期刊要求的LaTeX格式论文",
      scenarioEn: "Academic researchers needing to create LaTeX papers meeting journal requirements",
      problemFocus: "LaTeX排版复杂，期刊格式要求多，手动调整耗时",
      problemFocusEn: "LaTeX typesetting is complex, journal format requirements are numerous, manual adjustment is time-consuming",
      author: "ndpvt-web · 学术废物收容所推荐",
      likes: 61, views: "3.9K", comments: 8,
    },
    {
      title: "office-skills：Word/PPT/PDF文档生成",
      titleEn: "office-skills: Word/PPT/PDF Document Generation",
      role: "creator",
      tags: ["文档生成", "Word", "PPT", "PDF", "AI技能"],
      tagsEn: ["Document Generation", "Word", "PPT", "PDF", "AI Skill"],
      content: `## office-skills Skill 使用指南\n\n### 核心定位\n覆盖Word、PPTX、PDF三个方向的文档生成skill。\n\n### 能力范围\n- Word文档自动生成\n- PPT演示文稿生成\n- PDF报告导出\n- 格式模板应用\n\n### 追踪来源\nGitHub: https://github.com/tfriedel/claude-office-skills\n官方docx/pptx/pdf: https://github.com/anthropics/skills`,
      description: "覆盖Word/PPT/PDF三方向的文档生成skill，支持格式模板应用",
      descriptionEn: "Document generation skill covering Word/PPT/PDF with format template support",
      scenario: "需要快速生成多种格式办公文档的用户",
      scenarioEn: "Users needing to quickly generate various format office documents",
      problemFocus: "文档格式转换复杂，排版不一致，多格式输出困难",
      problemFocusEn: "Document format conversion is complex, layout inconsistency, multi-format output is difficult",
      author: "tfriedel · 学术废物收容所推荐",
      likes: 53, views: "3.5K", comments: 7,
    },
    {
      title: "research-superpower：研究超能力增强",
      titleEn: "research-superpower: Research Superpower Enhancement",
      role: "researcher",
      tags: ["学术研究", "研究增强", "文献检索", "AI技能"],
      tagsEn: ["Academic Research", "Research Enhancement", "Literature Search", "AI Skill"],
      content: `## research-superpower Skill 使用指南\n\n### 核心定位\n研究超能力增强skill，在选题阶段配合research-proposal使用。\n\n### 能力范围\n- 文献自动检索\n- 引用校验\n- 研究趋势分析\n- 竞争对手跟踪\n\n### 使用方式\n选题阶段：research-proposal起草 → superpower校验引用 → strategist调整结构\n\n### 追踪来源\nGitHub: https://github.com/kthorn/research-superpower`,
      description: "研究超能力增强skill，支持文献自动检索、引用校验和研究趋势分析",
      descriptionEn: "Research superpower enhancement skill, supporting auto literature search, citation verification, and research trend analysis",
      scenario: "学术研究者需要高效检索文献和校验引用",
      scenarioEn: "Academic researchers needing efficient literature search and citation verification",
      problemFocus: "文献检索耗时长，引用格式错误多，研究趋势把握不准",
      problemFocusEn: "Literature search is time-consuming, citation format errors are frequent, research trends are hard to grasp",
      author: "kthorn · 学术废物收容所推荐",
      likes: 58, views: "3.8K", comments: 8,
    },
  ];

  // ===== Skills from Article 5: 8 Best Skills (5 new after dedup) =====
  const bestSkills = [
    {
      title: "skill-vetter：Skill安全审查防投毒",
      titleEn: "skill-vetter: Skill Security Review & Poisoning Prevention",
      role: "developer",
      tags: ["Claude Code", "安全审查", "Skill投毒", "恶意检测", "AI技能"],
      tagsEn: ["Claude Code", "Security Review", "Skill Poisoning", "Malware Detection", "AI Skill"],
      content: `## skill-vetter 使用指南\n\n### 核心定位\nClawHub上10000+个Skill鱼龙混杂，skill-vetter帮你审查Skill安全性。\n\n### 背景案例\nhightower6eu发布314个Skill，全是恶意的。套路：装完后让你去陌生地址下载东西，然后直接在你电脑上执行。\n\n### 风险等级\n- 低风险：做笔记、查天气、格式处理\n- 中风险：文件操作、浏览器控制、调外部API\n- 高风险：执行系统命令、网络请求、文件修改\n- 极高风险：下载执行远程文件、权限提升\n\n### 使用方式\n装任何Skill之前先扫一遍，出一份报告告诉你能不能装。\n\n### 追踪来源\nhttps://clawhub.ai/spclaudehome/skill-vetter`,
      description: "Claude Code Skill安全审查工具，四级风险检测，防止恶意Skill投毒",
      descriptionEn: "Claude Code skill security review tool with four-level risk detection, preventing malicious skill poisoning",
      scenario: "Claude Code用户需要安全审查从第三方安装的Skill",
      scenarioEn: "Claude Code users needing to security review third-party installed skills",
      problemFocus: "第三方Skill可能包含恶意代码，安装后窃取API Key或执行恶意操作",
      problemFocusEn: "Third-party skills may contain malicious code, stealing API keys or executing malicious operations after installation",
      author: "spclaudehome · 顾小北推荐",
      likes: 108, views: "7.8K", comments: 17,
    },
    {
      title: "last30days：海外社区真实情绪抓取",
      titleEn: "last30days: Overseas Community Real Sentiment Capture",
      role: "growth",
      tags: ["社区调研", "情绪分析", "竞品分析", "选品调研", "AI技能"],
      tagsEn: ["Community Research", "Sentiment Analysis", "Competitor Analysis", "Product Research", "AI Skill"],
      content: `## last30days Skill 使用指南\n\n### 核心定位\n深入10+海外社区平台，抓取最近30天真实讨论，带参与度数据。\n\n### 覆盖平台\nReddit、X(Twitter)、YouTube、Hacker News、TikTok、Polymarket\n\n### 核心差异（vs Perplexity）\nPerplexity搜的是SEO排名靠前的网页，last30days抓的是社区真实参与度。\n\n### 使用方式\n\`\`\`bash\n/last30days 这个产品在美国市场反馈\n\`\`\`\n2-5分钟输出带引用来源的综合报告。\n\n### 适用场景\n- 跨境电商选品调研\n- 竞品分析\n- 话题追踪\n- 市场进入决策\n\n### 追踪来源\nGitHub: https://github.com/mvanhorn/last30days-skill\n作者: Lyft联合创始人，8000+星`,
      description: "深入10+海外社区抓取真实讨论和参与度数据，2-5分钟输出综合调研报告",
      descriptionEn: "Deep dive into 10+ overseas communities for real discussions and engagement data, comprehensive report in 2-5 minutes",
      scenario: "跨境电商、市场分析师需要了解海外真实社区反馈",
      scenarioEn: "Cross-border e-commerce and market analysts needing to understand overseas community feedback",
      problemFocus: "传统搜索看到的是SEO优化内容，不是真实用户反馈",
      problemFocusEn: "Traditional search shows SEO-optimized content, not real user feedback",
      author: "mvanhorn · 顾小北推荐",
      likes: 92, views: "6.5K", comments: 14,
    },
    {
      title: "self-improving-agent：从失败中自我进化",
      titleEn: "self-improving-agent: Self-Evolution from Failure",
      role: "developer",
      tags: ["Claude Code", "自我进化", "错误学习", "AI技能"],
      tagsEn: ["Claude Code", "Self-Evolution", "Error Learning", "AI Skill"],
      content: `## self-improving-agent 使用指南\n\n### 核心定位\n主动捕获执行错误和你的纠正指令，让Agent在失败中持续进化。ClawHub热门榜第一，46k+ installs。\n\n### 工作原理\n1. 捕获执行过程中的错误\n2. 记录用户的纠正指令\n3. 自动调整后续行为\n4. 形成个人化的工作模式\n\n### 核心价值\n装上一周后，你会发现它真的变聪明了。模型没升级，是它记住了你的习惯、偏好、之前的判断。\n\n### 追踪来源\nhttps://clawhub.ai/pskoett/self-improving-agent`,
      description: "主动捕获错误和学习纠正指令的Agent进化skill，ClawHub 46k+ installs",
      descriptionEn: "Agent evolution skill that actively captures errors and learns from corrections, ClawHub 46k+ installs",
      scenario: "需要AI助手持续学习用户习惯并自我改进的重度用户",
      scenarioEn: "Heavy users needing AI assistants to continuously learn user habits and self-improve",
      problemFocus: "AI助手每次从零开始，记不住用户偏好和之前纠正过的问题",
      problemFocusEn: "AI assistants start from scratch each time, unable to remember user preferences and previously corrected issues",
      author: "pskoett · 顾小北推荐",
      likes: 145, views: "10.2K", comments: 23,
    },
    {
      title: "claude-to-im：飞书远程操控Claude Code",
      titleEn: "claude-to-im: Feishu Remote Control for Claude Code",
      role: "operations",
      tags: ["Claude Code", "飞书", "远程操控", "即时通讯", "AI技能"],
      tagsEn: ["Claude Code", "Feishu", "Remote Control", "IM", "AI Skill"],
      content: `## claude-to-im Skill 使用指南\n\n### 核心定位\n把Claude Code桥接到飞书，出门在外用手机在飞书里发消息，就能远程操控电脑上的Claude Code。\n\n### 能干嘛\n- 躺床上让它帮你整理文档\n- 出差路上发现需要改个脚本\n- 开会时临时要查个数据\n- 晚上想起来有个代码要推送\n\n### 飞书优势\n- 不需要公网IP\n- 不需要内网穿透\n- 防火墙后面也能用\n- 配置简单\n\n### 追踪来源\nGitHub: https://github.com/op7418/Claude-to-IM-skill`,
      description: "将Claude Code桥接到飞书，支持手机远程操控和团队协作共用",
      descriptionEn: "Bridges Claude Code to Feishu, supporting mobile remote control and team collaboration",
      scenario: "需要随时随地远程操控Claude Code的用户",
      scenarioEn: "Users needing to remotely control Claude Code anytime, anywhere",
      problemFocus: "Claude Code必须坐在电脑前使用，出门在外无法操作",
      problemFocusEn: "Claude Code requires sitting at a computer, unusable when away from desk",
      author: "op7418 · 顾小北推荐",
      likes: 87, views: "5.8K", comments: 13,
    },
  ];

  // ===== Prompts from Article 6: 20 Claude Prompts =====
  const claudePrompts = [
    // 深度研究(1-4)
    { title: "多源信息融合：3分钟读完90分钟的内容", titleEn: "Multi-Source Synthesis: Read 90min Content in 3min", role: "researcher", tags: ["深度研究", "信息融合", "多源分析", "Claude提示词"], tagsEn: ["Deep Research", "Info Fusion", "Multi-Source", "Claude Prompt"], content: "你是一名资深研究分析师。你的任务是将多个来源的信息融合成一份权威简报...", description: "将多篇来源融合为一份权威简报，自动识别共识、冲突和盲区，3分钟完成90分钟的阅读", descriptionEn: "Fuses multiple sources into an authoritative brief, auto-identifying consensus, conflicts, and gaps, completing 90min reading in 3min", scenario: "研究人员、决策者需要快速综合多篇资料形成结论", scenarioEn: "Researchers and decision-makers needing to quickly synthesize multiple sources into conclusions", problemFocus: "一篇篇分开读效率低，容易遗漏关键冲突和盲区", problemFocusEn: "Reading sources individually is inefficient, easily missing key conflicts and blind spots", author: "大迁世界 · 20个Claude提示词", likes: 156, views: "12.5K", comments: 28 },
    { title: "魔鬼代言人模式：在决策前击碎你的想法", titleEn: "Devil's Advocate Mode: Crush Your Idea Before Deciding", role: "strategist", tags: ["批判思维", "决策验证", "风险评估", "Claude提示词"], tagsEn: ["Critical Thinking", "Decision Validation", "Risk Assessment", "Claude Prompt"], content: "你是一个言辞犀利、毫不留情的批判者。你的唯一任务就是彻底击碎这个想法...", description: "让AI以最犀利的逻辑攻击你的想法，找出可能置你于死地的地雷", descriptionEn: "Let AI attack your ideas with the sharpest logic, finding landmines that could destroy you", scenario: "创业者、产品经理在做重大决策前需要充分的压力测试", scenarioEn: "Entrepreneurs and PMs needing thorough stress testing before major decisions", problemFocus: "人们容易对自己的想法过于乐观，忽视关键风险和假设漏洞", problemFocusEn: "People tend to be overly optimistic about their ideas, overlooking key risks and assumption flaws", author: "大迁世界 · 20个Claude提示词", likes: 134, views: "10.8K", comments: 22 },
    { title: "强力推演对手：构建最无懈可击的对方立场", titleEn: "Steelman Any Position: Build the Strongest Opposing View", role: "strategist", tags: ["批判思维", "立场分析", "辩论准备", "Claude提示词"], tagsEn: ["Critical Thinking", "Position Analysis", "Debate Prep", "Claude Prompt"], content: "我不同意这个立场。请为对方的立场构建一个最强、最无懈可击的钢人模型...", description: "让AI替你反对的观点辩护，构建最聪明的版本，知己知彼不被意外击败", descriptionEn: "Let AI defend the position you oppose, building the smartest version so you know your opponent", scenario: "辩论准备、投资决策、产品方向争论前需要理解对方最强论点", scenarioEn: "Before debates, investment decisions, or product direction disputes, needing to understand the strongest opposing arguments", problemFocus: "人们倾向于攻击对方观点最弱的版本，而不是最强的版本", problemFocusEn: "People tend to attack the weakest version of opposing views, not the strongest", author: "大迁世界 · 20个Claude提示词", likes: 98, views: "7.8K", comments: 16 },
    { title: "底层思维模型构建器：十分钟讲透任何领域", titleEn: "Mental Model Builder: Master Any Field in Ten Minutes", role: "researcher", tags: ["思维模型", "快速学习", "知识框架", "Claude提示词"], tagsEn: ["Mental Model", "Rapid Learning", "Knowledge Framework", "Claude Prompt"], content: "你是一位世界级的顶级导师。请用3-5个思维模型来讲解这个主题...", description: "将任何领域拆解为互相关联的底层思维模型，十分钟就能讲给别人听", descriptionEn: "Breaks any field into interconnected mental models, enabling you to teach it to others in ten minutes", scenario: "需要快速理解新领域并建立知识框架的学习者", scenarioEn: "Learners needing to quickly understand new fields and build knowledge frameworks", problemFocus: "传统学习方式堆砌事实，缺乏可迁移的思维框架", problemFocusEn: "Traditional learning stacks facts without transferable mental frameworks", author: "大迁世界 · 20个Claude提示词", likes: 112, views: "8.9K", comments: 18 },
    // 写作(5-8)
    { title: "文风精准复刻：AI写出完全属于你的声音", titleEn: "Style Mimic: AI Writes in Your Unique Voice", role: "writer", tags: ["写作", "文风分析", "内容创作", "Claude提示词"], tagsEn: ["Writing", "Style Analysis", "Content Creation", "Claude Prompt"], content: "你是一位风格分析师和金牌撰稿人。请学习我的写作风格然后精准复刻它...", description: "让AI深度分析你的3篇样本文章，精准复刻你的文风为新主题创作", descriptionEn: "Let AI deeply analyze 3 sample articles of yours, precisely mimicking your writing style for new topics", scenario: "内容创作者需要保持一致的写作风格，同时提高产出效率", scenarioEn: "Content creators needing to maintain consistent writing style while increasing output efficiency", problemFocus: "AI写作风格千篇一律，缺乏个人特色，需要大量修改", problemFocusEn: "AI writing styles are generic, lacking personal touch, requiring extensive editing", author: "大迁世界 · 20个Claude提示词", likes: 87, views: "6.8K", comments: 14 },
    { title: "铁血主编：血淋淋地去粗取精", titleEn: "The Brutal Editor: Ruthless Editing for Quality", role: "writer", tags: ["写作", "编辑审校", "内容优化", "Claude提示词"], tagsEn: ["Writing", "Editing", "Content Optimization", "Claude Prompt"], content: "你是我遇到过最严苛的铁血主编。请客观评估我的初稿...", description: "让AI以铁血主编的身份彻底撕碎你的初稿，去粗取精", descriptionEn: "Let AI ruthlessly tear apart your draft as a brutal editor, cutting the fat and keeping the meat", scenario: "写作者需要对初稿进行高质量的自我编辑和审校", scenarioEn: "Writers needing high-quality self-editing and proofreading of drafts", problemFocus: "自我编辑容易心软，看不出自己文章的废话和软弱观点", problemFocusEn: "Self-editing tends to be lenient, unable to spot fluff and weak arguments in own writing", author: "大迁世界 · 20个Claude提示词", likes: 76, views: "5.9K", comments: 12 },
    { title: "一稿五用：同一观点写给5个不同受众", titleEn: "One Draft Five Ways: Same Idea for 5 Different Audiences", role: "writer", tags: ["写作", "受众适配", "内容复用", "Claude提示词"], tagsEn: ["Writing", "Audience Adaptation", "Content Repurposing", "Claude Prompt"], content: "你是一位沟通大师。请将同一个核心观点精准翻译给完全不同的受众...", description: "将同一核心观点改写为5个不同受众版本：小白、专家、杠精、记者、高管", descriptionEn: "Rewrite the same core idea into 5 audience versions: beginner, expert, skeptic, journalist, executive", scenario: "营销人员、产品经理需要同一内容适配不同受众", scenarioEn: "Marketers and PMs needing to adapt the same content for different audiences", problemFocus: "为不同受众重写内容耗时且容易丢失核心信息", problemFocusEn: "Rewriting for different audiences is time-consuming and core messages can get lost", author: "大迁世界 · 20个Claude提示词", likes: 82, views: "6.2K", comments: 13 },
    { title: "提纲秒变爆款：零散笔记变完整作品", titleEn: "Bullets to Article: Scattered Notes to Polished Piece", role: "writer", tags: ["写作", "内容生成", "笔记整理", "Claude提示词"], tagsEn: ["Writing", "Content Generation", "Note Organization", "Claude Prompt"], content: "你是一位顶级的职业撰稿人。请将我的零散笔记转化成一篇逻辑严密的作品...", description: "将零散笔记加工为结构完整、行文流畅的作品，不丢失任何想法", descriptionEn: "Transform scattered notes into structurally complete, smoothly written pieces without losing any ideas", scenario: "内容创作者有碎片化想法但缺乏整理成完整文章的能力", scenarioEn: "Content creators have fragmented ideas but lack ability to organize them into complete articles", problemFocus: "从零散笔记到完整文章的过程耗时且容易遗漏关键点", problemFocusEn: "The process from scattered notes to complete article is time-consuming and key points can be missed", author: "大迁世界 · 20个Claude提示词", likes: 91, views: "7.1K", comments: 15 },
    // 职场进阶(9-11)
    { title: "薪资谈判沙盘推演：练完再上真战场", titleEn: "Salary Negotiation Sandbox: Practice Before the Real Battle", role: "operations", tags: ["薪资谈判", "模拟演练", "职场进阶", "Claude提示词"], tagsEn: ["Salary Negotiation", "Simulation", "Career", "Claude Prompt"], content: "你是一家公司的HR。你经验丰富、绝不轻易妥协。请跟我进行薪资谈判模拟...", description: "与AI进行高度真实的薪资谈判模拟，HR会抛出经典拒绝理由并疯狂压价", descriptionEn: "Engage in highly realistic salary negotiation simulation with AI, HR throws classic rejection reasons and hard bargaining", scenario: "求职者在收到Offer后需要充分准备薪资谈判", scenarioEn: "Job seekers needing thorough preparation for salary negotiation after receiving offers", problemFocus: "大多数人谈薪水时吃亏是因为缺乏练习，不知道如何应对HR的压价策略", problemFocusEn: "Most people lose in salary negotiations due to lack of practice, not knowing how to handle HR pressure tactics", author: "大迁世界 · 20个Claude提示词", likes: 118, views: "9.2K", comments: 19 },
    { title: "面试模拟器：练完三轮保持淡定", titleEn: "Interview Simulator: Stay Calm After Three Rounds", role: "operations", tags: ["面试准备", "模拟面试", "职场进阶", "Claude提示词"], tagsEn: ["Interview Prep", "Mock Interview", "Career", "Claude Prompt"], content: "你是一位资深面试官。请主持一场高度逼真的求职面试，一次只提一个问题...", description: "AI担任面试官，针对岗位抛出刁钻问题并给出结构化反馈和评分", descriptionEn: "AI acts as interviewer, asking tough position-specific questions and providing structured feedback and scoring", scenario: "求职者准备面试时需要针对性的练习和反馈", scenarioEn: "Job seekers needing targeted practice and feedback for interview preparation", problemFocus: "面试紧张导致发挥失常，不知道如何回答刁钻问题", problemFocusEn: "Interview nerves lead to poor performance, not knowing how to answer tricky questions", author: "大迁世界 · 20个Claude提示词", likes: 105, views: "8.5K", comments: 17 },
    { title: "简历超级放大镜：一简历投天下→精准定制", titleEn: "Resume Super Magnifier: One Resume to Custom Versions", role: "operations", tags: ["简历优化", "求职", "职场进阶", "Claude提示词"], tagsEn: ["Resume Optimization", "Job Hunting", "Career", "Claude Prompt"], content: "你是一位顶级的职业简历撰稿人。请针对不同岗位生成3个精准定制的简历版本...", description: "根据3个不同岗位描述，生成3个精准定制的简历版本，每个放大该岗位最看重的经历", descriptionEn: "Generate 3 precisely tailored resume versions based on different job descriptions, amplifying each role's most valued experiences", scenario: "求职者需要针对不同岗位定制简历但时间有限", scenarioEn: "Job seekers needing to tailor resumes for different positions but with limited time", problemFocus: "一份简历投所有岗位导致石沉大海，没有针对性", problemFocusEn: "Sending one resume to all positions leads to no responses, lacking targeting", author: "大迁世界 · 20个Claude提示词", likes: 89, views: "6.9K", comments: 14 },
    // 生活教练(12-17)
    { title: "AI健身私教：个性化训练计划生成", titleEn: "AI Fitness Coach: Personalized Training Plan", role: "operations", tags: ["健身", "个人训练", "健康管理", "Claude提示词"], tagsEn: ["Fitness", "Personal Training", "Health", "Claude Prompt"], content: "你是一位顶级的NSCA认证私人教练。请为我设计一套科学可行的健身与饮食计划...", description: "基于个人信息的个性化健身与饮食计划，含动作替代方案和进阶规则", descriptionEn: "Personalized fitness and nutrition plan based on personal info, with exercise alternatives and progression rules", scenario: "健身爱好者需要科学可行的个性化训练计划", scenarioEn: "Fitness enthusiasts needing scientific, feasible personalized training plans", problemFocus: "网上训练计划千篇一律，不适合个人情况，容易受伤或无效", problemFocusEn: "Online training plans are one-size-fits-all, unsuitable for individual conditions, leading to injury or ineffectiveness", author: "大迁世界 · 20个Claude提示词", likes: 76, views: "5.8K", comments: 12 },
    { title: "AI营养师：7天饮食计划+购物清单", titleEn: "AI Nutritionist: 7-Day Meal Plan + Shopping List", role: "operations", tags: ["营养", "饮食计划", "健康", "Claude提示词"], tagsEn: ["Nutrition", "Meal Plan", "Health", "Claude Prompt"], content: "你是一位顶级的营养师。请帮我制定一份7天饮食计划，包含购物清单和备菜指南...", description: "基于个人限制的7天饮食计划，含热量标注、购物清单和备菜指南", descriptionEn: "7-day meal plan based on personal restrictions, with calorie labels, shopping list, and meal prep guide", scenario: "需要控制饮食或有特殊饮食需求的人群", scenarioEn: "People needing diet control or with special dietary requirements", problemFocus: "制定饮食计划繁琐，不了解营养搭配，购物清单管理混乱", problemFocusEn: "Creating meal plans is tedious, nutrition pairing is unclear, shopping list management is chaotic", author: "大迁世界 · 20个Claude提示词", likes: 68, views: "5.1K", comments: 10 },
    { title: "法律条款大白话翻译器：签字前搞清楚", titleEn: "Legal Jargon Translator: Understand Before Signing", role: "operations", tags: ["法律", "合同审查", "消费者权益", "Claude提示词"], tagsEn: ["Legal", "Contract Review", "Consumer Rights", "Claude Prompt"], content: "我需要签一份法律文件。请用大白话翻译这份文件，从6个维度帮我扒个底朝天...", description: "将法律合同翻译为大白话，识别潜在火坑和缺失条款，签字前必问问题清单", descriptionEn: "Translates legal contracts into plain language, identifying potential traps and missing clauses, with pre-signing question checklist", scenario: "普通人在签署合同、租约前需要理解条款含义", scenarioEn: "Ordinary people needing to understand contract terms before signing", problemFocus: "法律术语看不懂，签了霸王条款也不知道", problemFocusEn: "Legal jargon is incomprehensible, people sign unfair clauses without knowing", author: "大迁世界 · 20个Claude提示词", likes: 92, views: "7.2K", comments: 15 },
    { title: "个人账单透视眼：刀刀见血的花钱黑洞", titleEn: "Personal Expense X-Ray: Bloody Spending Black Holes", role: "operations", tags: ["财务", "消费分析", "理财", "Claude提示词"], tagsEn: ["Finance", "Spending Analysis", "Money Management", "Claude Prompt"], content: "你是一位顶级的个人财务分析师。请审视我真实的消费数据，给我一份见血的诊断...", description: "基于真实消费数据的财务诊断，找出3大出血口和快速回血方案", descriptionEn: "Financial diagnosis based on real spending data, finding 3 major bleeding points and quick recovery plans", scenario: "需要管理个人财务、实现理财目标的上班族", scenarioEn: "Working professionals needing to manage personal finances and achieve money goals", problemFocus: "不知道钱花哪了，理财建议太空洞没有针对性", problemFocusEn: "Don't know where money goes, financial advice is too generic without specificity", author: "大迁世界 · 20个Claude提示词", likes: 84, views: "6.5K", comments: 13 },
    { title: "拒绝踩坑的旅行规划：本地人独家路线", titleEn: "Travel Planning Without Pitfalls: Local Exclusive Routes", role: "operations", tags: ["旅行", "行程规划", "预算控制", "Claude提示词"], tagsEn: ["Travel", "Itinerary Planning", "Budget Control", "Claude Prompt"], content: "你是一位对目的地了如指掌的资深旅行专家。请为我量身定制一份行程...", description: "基于个人旅行风格的定制化行程规划，含避坑提示和预算明细", descriptionEn: "Customized itinerary planning based on personal travel style, with pitfall avoidance and budget breakdown", scenario: "旅行前需要量身定制行程，避开游客陷阱", scenarioEn: "Travelers needing tailored itineraries before trips, avoiding tourist traps", problemFocus: "网上攻略千篇一律，不知道哪些是真的推荐哪些是广告", problemFocusEn: "Online guides are all the same, unsure which are real recommendations vs ads", author: "大迁世界 · 20个Claude提示词", likes: 72, views: "5.4K", comments: 11 },
    { title: "30天硬核学习计划：从新手到产出一个作品", titleEn: "30-Day Hardcore Learning Plan: From Novice to Deliverable", role: "operations", tags: ["学习", "技能习得", "项目制学习", "Claude提示词"], tagsEn: ["Learning", "Skill Acquisition", "Project-Based Learning", "Claude Prompt"], content: "你是一位世界级的学习设计师。请为我制定一份30天以产出为导向的硬核学习计划...", description: "以产出为导向的30天学习计划，每周有里程碑考核，80%实践20%理论", descriptionEn: "Output-oriented 30-day learning plan with weekly milestone assessments, 80% practice 20% theory", scenario: "想快速学会一项新技能并产出可展示作品的学习者", scenarioEn: "Learners wanting to quickly acquire a new skill and produce a showcase piece", problemFocus: "学习计划空洞不具体，只学不练，30天后什么也没有产出", problemFocusEn: "Learning plans are vague and impractical, only learning without practice, nothing produced after 30 days", author: "大迁世界 · 20个Claude提示词", likes: 98, views: "7.8K", comments: 16 },
    // 思辨(18-20)
    { title: "苏格拉底式对话：用提问逼你想透问题", titleEn: "Socratic Dialogue: Force Deep Thinking Through Questions", role: "researcher", tags: ["思辨", "苏格拉底", "深度学习", "Claude提示词"], tagsEn: ["Critical Thinking", "Socrates", "Deep Learning", "Claude Prompt"], content: "你是一位苏格拉底式的导师。你绝对不直接给我答案，你只向我提问...", description: "AI作为苏格拉底式导师，只提问不给答案，引导你自己想透问题", descriptionEn: "AI acts as Socratic mentor, only asking questions without giving answers, guiding you to think through problems yourself", scenario: "需要深度理解某个主题而不是浅层知道的学习者", scenarioEn: "Learners needing deep understanding of a topic rather than superficial knowledge", problemFocus: "直接要答案无法真正理解，知识留存率低", problemFocusEn: "Getting direct answers doesn't lead to true understanding, knowledge retention is low", author: "大迁世界 · 20个Claude提示词", likes: 145, views: "11.2K", comments: 24 },
    { title: "终极反共识猎人：发现未被人注意的真相", titleEn: "Ultimate Contrarian Hunter: Discover Unnoticed Truths", role: "strategist", tags: ["思辨", "反共识", "深度思考", "Claude提示词"], tagsEn: ["Critical Thinking", "Contrarian", "Deep Thinking", "Claude Prompt"], content: "你是一个终极反共识猎人。请找出[主题]领域中所有人都相信但实际上可能是错的信念...", description: "发现领域内所有人都相信但可能是错的信念，寻找被忽视的非共识观点", descriptionEn: "Discover beliefs everyone holds but might be wrong, seeking overlooked non-consensus views", scenario: "投资者、战略家需要发现市场共识中的盲点和错误假设", scenarioEn: "Investors and strategists needing to discover blind spots and false assumptions in market consensus", problemFocus: "群体思维导致重要观点被忽视，共识往往意味着机会已经被挖掘", problemFocusEn: "Groupthink causes important views to be overlooked, consensus often means opportunity is already mined", author: "大迁世界 · 20个Claude提示词", likes: 87, views: "6.8K", comments: 14 },
    { title: "时间旅行者：从历史中找答案", titleEn: "Time Traveler: Find Answers from History", role: "strategist", tags: ["思辨", "历史借鉴", "模式识别", "Claude提示词"], tagsEn: ["Critical Thinking", "Historical Learning", "Pattern Recognition", "Claude Prompt"], content: "你是一位时间旅行者。请分析[主题]在历史上是否出现过类似的模式...", description: "从历史中寻找与当前问题相似的模式，借鉴古人智慧解决现代问题", descriptionEn: "Search history for patterns similar to current problems, learning from ancient wisdom to solve modern issues", scenario: "战略决策者需要从历史中寻找参照和启示", scenarioEn: "Strategic decision-makers needing to find references and insights from history", problemFocus: "人们倾向于忽视历史经验，重复犯同样的错误", problemFocusEn: "People tend to ignore historical experience, repeating the same mistakes", author: "大迁世界 · 20个Claude提示词", likes: 72, views: "5.6K", comments: 11 },
  ];

  // Insert all skills
  const allSkills = [...pptSkills, ...claudeSkills, ...ossSkills, ...academicSkills, ...bestSkills];
  console.log(`Inserting ${allSkills.length} skills...`);
  for (const s of allSkills) {
    await db.insert(skills).values(s);
  }

  // Insert all prompts
  console.log(`Inserting ${claudePrompts.length} prompts...`);
  for (const p of claudePrompts) {
    await db.insert(prompts).values(p as any);
  }

  console.log("Import complete!");
  process.exit(0);
}

importWechatContent().catch(console.error);
