import { getDb } from "../api/queries/connection";
import { skills } from "../db/schema";

async function importBatch() {
  const db = getDb();

  const batch = [
    // Andrej Karpathy Skills (5)
    {
      title: "claude-code-terminal: Terminal Development Enhancement",
      titleEn: "claude-code-terminal: Terminal Development Enhancement",
      role: "developer",
      tags: ["Claude Code", "Terminal", "CLI", "AI Skill"],
      tagsEn: ["Claude Code", "Terminal", "CLI", "AI Skill"],
      content: "Enhances Claude Code terminal development capabilities. Supports shell script generation and debugging, CLI tool development, terminal workflow automation, and system administration tasks.\n\nSource: Andrej Karpathy skills collection",
      description: "Enhance Claude Code terminal development with scripting",
      descriptionEn: "Enhance Claude Code terminal development with scripting",
      scenario: "Developers doing complex CLI development and automation",
      scenarioEn: "Developers doing complex CLI development and automation",
      problemFocus: "Terminal development is inefficient, scripting is error-prone",
      problemFocusEn: "Terminal development is inefficient, scripting is error-prone",
      author: "Andrej Karpathy Skills", likes: 87, views: "6.5K", comments: 11,
    },
    {
      title: "claude-code-browser: Browser Automation",
      titleEn: "claude-code-browser: Browser Automation",
      role: "developer",
      tags: ["Claude Code", "Browser Automation", "Web Scraping", "AI Skill"],
      tagsEn: ["Claude Code", "Browser Automation", "Web Scraping", "AI Skill"],
      content: "Lets Claude Code control browsers for automation. Supports browser automation control, web application testing, data scraping and collection, and webpage content analysis.\n\nSource: Andrej Karpathy skills collection",
      description: "Browser automation for web testing and data scraping",
      descriptionEn: "Browser automation for web testing and data scraping",
      scenario: "Developers needing web automated testing and data scraping",
      scenarioEn: "Developers needing web automated testing and data scraping",
      problemFocus: "Browser automation configuration is complex",
      problemFocusEn: "Browser automation configuration is complex",
      author: "Andrej Karpathy Skills", likes: 94, views: "7.1K", comments: 13,
    },
    {
      title: "claude-code-database: Database Operation Assistant",
      titleEn: "claude-code-database: Database Operation Assistant",
      role: "developer",
      tags: ["Claude Code", "Database", "SQL", "AI Skill"],
      tagsEn: ["Claude Code", "Database", "SQL", "AI Skill"],
      content: "Database operation enhancement skill. Supports SQL query generation and optimization, database schema analysis, data migration script generation, and performance bottleneck diagnosis.\n\nSource: Andrej Karpathy skills collection",
      description: "SQL generation, schema analysis and optimization",
      descriptionEn: "SQL generation, schema analysis and optimization",
      scenario: "Developers interacting with databases for queries",
      scenarioEn: "Developers interacting with databases for queries",
      problemFocus: "SQL writing is inefficient, optimization lacks experience",
      problemFocusEn: "SQL writing is inefficient, optimization lacks experience",
      author: "Andrej Karpathy Skills", likes: 78, views: "5.8K", comments: 10,
    },
    {
      title: "claude-code-debug: Debugging Expert",
      titleEn: "claude-code-debug: Debugging Expert",
      role: "developer",
      tags: ["Claude Code", "Debugging", "Bug Fix", "AI Skill"],
      tagsEn: ["Claude Code", "Debugging", "Bug Fix", "AI Skill"],
      content: "Debugging expert skill for quickly locating and analyzing root causes of code bugs. Supports error log analysis, breakpoint debugging assistance, root cause analysis, and fix recommendations.\n\nSource: Andrej Karpathy skills collection",
      description: "Quick bug localization and root cause analysis",
      descriptionEn: "Quick bug localization and root cause analysis",
      scenario: "Developers needing to quickly locate and fix bugs",
      scenarioEn: "Developers needing to quickly locate and fix bugs",
      problemFocus: "Bug localization is time-consuming, debugging lacks methodology",
      problemFocusEn: "Bug localization is time-consuming, debugging lacks methodology",
      author: "Andrej Karpathy Skills", likes: 102, views: "7.8K", comments: 15,
    },
    {
      title: "claude-code-deploy: Deployment Automation",
      titleEn: "claude-code-deploy: Deployment Automation",
      role: "developer",
      tags: ["Claude Code", "Deployment", "DevOps", "CI/CD", "AI Skill"],
      tagsEn: ["Claude Code", "Deployment", "DevOps", "CI/CD", "AI Skill"],
      content: "Deployment automation skill for one-click application deployment and CI/CD pipeline configuration. Supports deployment script generation, CI/CD flow configuration, containerization config, and environment management.\n\nSource: Andrej Karpathy skills collection",
      description: "One-click deployment and CI/CD configuration",
      descriptionEn: "One-click deployment and CI/CD configuration",
      scenario: "Developers automating deployment and CI/CD",
      scenarioEn: "Developers automating deployment and CI/CD",
      problemFocus: "Deployment has many manual steps, configuration is complex",
      problemFocusEn: "Deployment has many manual steps, configuration is complex",
      author: "Andrej Karpathy Skills", likes: 85, views: "6.2K", comments: 11,
    },
    // All-positions collection (5)
    {
      title: "hr-recruitment: AI Recruitment Assistant",
      titleEn: "hr-recruitment: AI Recruitment Assistant",
      role: "operations",
      tags: ["HR", "Recruitment", "Talent Screening", "Claude Code", "AI Skill"],
      tagsEn: ["HR", "Recruitment", "Talent Screening", "Claude Code", "AI Skill"],
      content: "AI recruitment assistant skill. Supports intelligent resume screening, candidate match scoring, interview question generation, and recruitment data analysis.\n\nSource: GitHub all-positions skill collection",
      description: "AI recruitment with resume screening and interview questions",
      descriptionEn: "AI recruitment with resume screening and interview questions",
      scenario: "HR efficiently screening large volumes of resumes",
      scenarioEn: "HR efficiently screening large volumes of resumes",
      problemFocus: "Resume screening is time-consuming, interview questions lack specificity",
      problemFocusEn: "Resume screening is time-consuming, interview questions lack specificity",
      author: "All-positions Skills", likes: 68, views: "4.8K", comments: 8,
    },
    {
      title: "legal-contract: Contract Review Assistant",
      titleEn: "legal-contract: Contract Review Assistant",
      role: "operations",
      tags: ["Legal", "Contract Review", "Compliance", "Claude Code", "AI Skill"],
      tagsEn: ["Legal", "Contract Review", "Compliance", "Claude Code", "AI Skill"],
      content: "Contract review assistant skill. Supports automatic contract clause review, risk point identification and annotation, compliance checking, and modification suggestions.\n\nSource: GitHub all-positions skill collection",
      description: "Automatic contract clause review and risk identification",
      descriptionEn: "Automatic contract clause review and risk identification",
      scenario: "Legal professionals reviewing large volumes of contracts",
      scenarioEn: "Legal professionals reviewing large volumes of contracts",
      problemFocus: "Contract review is time-consuming, key risks easily missed",
      problemFocusEn: "Contract review is time-consuming, key risks easily missed",
      author: "All-positions Skills", likes: 72, views: "5.1K", comments: 9,
    },
    {
      title: "customer-service: Customer Service AI Assistant",
      titleEn: "customer-service: Customer Service AI Assistant",
      role: "operations",
      tags: ["Customer Service", "AI Support", "Customer Support", "Claude Code", "AI Skill"],
      tagsEn: ["Customer Service", "AI Support", "Customer Support", "Claude Code", "AI Skill"],
      content: "Customer service AI assistant skill. Supports automatic customer issue classification, reply template generation, emotion recognition and calming, and ticket automatic assignment.\n\nSource: GitHub all-positions skill collection",
      description: "Auto issue classification and reply template generation",
      descriptionEn: "Auto issue classification and reply template generation",
      scenario: "Customer service teams handling large volumes of inquiries",
      scenarioEn: "Customer service teams handling large volumes of inquiries",
      problemFocus: "Low reply efficiency, lack of standardized complaint handling",
      problemFocusEn: "Low reply efficiency, lack of standardized complaint handling",
      author: "All-positions Skills", likes: 64, views: "4.5K", comments: 7,
    },
    {
      title: "data-analyst: Data Analysis Assistant",
      titleEn: "data-analyst: Data Analysis Assistant",
      role: "dataScientist",
      tags: ["Data Analysis", "Report Generation", "Visualization", "Claude Code", "AI Skill"],
      tagsEn: ["Data Analysis", "Report Generation", "Visualization", "Claude Code", "AI Skill"],
      content: "Data analysis assistant skill for quickly completing data cleaning, analysis, and report generation. Supports data cleaning and preprocessing, statistical analysis, visualization chart generation, and automatic report output.\n\nSource: GitHub all-positions skill collection",
      description: "Data cleaning, analysis and report generation",
      descriptionEn: "Data cleaning, analysis and report generation",
      scenario: "Data analysts processing data and generating reports",
      scenarioEn: "Data analysts processing data and generating reports",
      problemFocus: "Repetitive data processing, time-consuming report creation",
      problemFocusEn: "Repetitive data processing, time-consuming report creation",
      author: "All-positions Skills", likes: 81, views: "5.9K", comments: 10,
    },
    {
      title: "content-marketing: Content Marketing Assistant",
      titleEn: "content-marketing: Content Marketing Assistant",
      role: "growth",
      tags: ["Content Marketing", "Social Media", "Copywriting", "Claude Code", "AI Skill"],
      tagsEn: ["Content Marketing", "Social Media", "Copywriting", "Claude Code", "AI Skill"],
      content: "Content marketing assistant skill for efficiently producing social media content and marketing copy. Supports social media copy generation, marketing plan creation, content calendar planning, and performance analysis.\n\nSource: GitHub all-positions skill collection",
      description: "Social media copy and marketing plan generation",
      descriptionEn: "Social media copy and marketing plan generation",
      scenario: "Marketing teams producing large volumes of social content",
      scenarioEn: "Marketing teams producing large volumes of social content",
      problemFocus: "Content creation is time-consuming, plans lack creativity",
      problemFocusEn: "Content creation is time-consuming, plans lack creativity",
      author: "All-positions Skills", likes: 76, views: "5.3K", comments: 9,
    },
  ];

  for (const s of batch) {
    await db.insert(skills).values(s);
  }
  console.log(`Inserted ${batch.length} skills (batch 3c)`);
  process.exit(0);
}

importBatch().catch(console.error);
