import { getDb } from "../api/queries/connection";
import { skills } from "../db/schema";

async function importBatch3() {
  const db = getDb();
  console.log("Importing batch 3: 13 WeChat articles...");

  const newSkills = [
    // ===== 文章1: Context Engineering 上下文工程 =====
    {
      title: "context-engineering：上下文工程精准控制",
      titleEn: "context-engineering: Precise Context Control",
      role: "developer",
      tags: ["Claude Code", "上下文工程", "Prompt工程", "AI技能"],
      tagsEn: ["Claude Code", "Context Engineering", "Prompt Engineering", "AI Skill"],
      content: `## context-engineering 使用指南\n\n### 核心定位\n上下文工程（Context Engineering）是Prompt Engineering的进化版——它不只是优化一句提示词，而是系统性管理AI获取的全部上下文信息，让输出从"靠运气"变成"可预期"。\n\n### 核心理念\n当AI输出不可控时，问题往往不是prompt写得不好，而是上下文给得太随意。Context Engineering通过结构化、分层的上下文管理，让AI每次都能精准理解你的意图。\n\n### 适用场景\n- 复杂项目开发中需要AI持续理解项目架构\n- 多轮对话中保持上下文连贯性\n- 需要AI在大量信息中精准定位关键内容\n- 团队协作中统一AI的工作模式\n\n### 追踪来源\nhttps://mp.weixin.qq.com/s/On69fuwyaa-KXauEjkcAjg`,
      description: "上下文工程skill，系统性管理AI获取的全部上下文信息，让输出从靠运气变成可预期",
      descriptionEn: "Context Engineering skill for systematically managing all context AI receives, making output predictable rather than luck-dependent",
      scenario: "复杂项目开发中需要AI持续理解项目架构和多轮对话连贯性",
      scenarioEn: "Complex project development requiring AI to continuously understand project architecture and maintain multi-turn conversation coherence",
      problemFocus: "AI输出不可控，问题不是prompt写得不好，而是上下文给得太随意",
      problemFocusEn: "AI output is uncontrollable; the issue isn't poor prompts but overly casual context provision",
      author: "GitHub精选 Skills",
      likes: 89, views: "6.5K", comments: 12,
    },

    // ===== 文章2: PM Skills 8个产品经理技能 =====
    {
      title: "pm-planning：产品规划与功能拆解",
      titleEn: "pm-planning: Product Planning & Feature Breakdown",
      role: "productManager",
      tags: ["产品经理", "产品规划", "功能拆解", "Claude Code", "AI技能"],
      tagsEn: ["Product Manager", "Product Planning", "Feature Breakdown", "Claude Code", "AI Skill"],
      content: `## pm-planning 使用指南\n\n### 核心定位\n产品规划与功能拆解skill，帮助产品经理将模糊的需求转化为清晰的开发计划。\n\n### 能力范围\n- 需求分析和优先级排序\n- 功能模块拆解和依赖关系梳理\n- 开发工作量估算\n- 里程碑规划\n\n### 适用场景\n- 新产品从零到一的规划\n- 版本迭代的功能梳理\n- 技术方案的产品侧输入\n\n### 追踪来源\nhttps://github.com/pmoser/pm-skills`,
      description: "产品规划与功能拆解skill，将模糊需求转化为清晰的开发计划和里程碑",
      descriptionEn: "Product planning and feature breakdown skill, transforming vague requirements into clear development plans and milestones",
      scenario: "产品经理需要从零规划新产品或梳理版本迭代功能",
      scenarioEn: "Product managers needing to plan new products from scratch or organize version iteration features",
      problemFocus: "需求模糊导致开发计划不清晰，功能优先级混乱",
      problemFocusEn: "Vague requirements lead to unclear development plans and chaotic feature prioritization",
      author: "pmoser · GitHub Skills推荐",
      likes: 76, views: "5.2K", comments: 9,
    },
    {
      title: "pm-prd：PRD文档生成与评审",
      titleEn: "pm-prd: PRD Document Generation & Review",
      role: "productManager",
      tags: ["产品经理", "PRD", "需求文档", "Claude Code", "AI技能"],
      tagsEn: ["Product Manager", "PRD", "Requirements Document", "Claude Code", "AI Skill"],
      content: `## pm-prd 使用指南\n\n### 核心定位\nPRD（产品需求文档）生成与评审skill，帮助产品经理快速产出高质量的需求文档。\n\n### 能力范围\n- PRD结构自动生成\n- 需求描述规范化\n- 验收标准制定\n- 交互流程图建议\n\n### 适用场景\n- 需要快速产出PRD\n- PRD评审前自检\n- 需求文档规范化\n\n### 追踪来源\nhttps://github.com/pmoser/pm-skills`,
      description: "PRD文档生成与评审skill，快速产出高质量的产品需求文档",
      descriptionEn: "PRD document generation and review skill for quickly producing high-quality product requirement documents",
      scenario: "产品经理需要快速产出规范的PRD文档",
      scenarioEn: "Product managers needing to quickly produce standardized PRD documents",
      problemFocus: "PRD写作耗时长，格式不统一，需求描述不清晰",
      problemFocusEn: "PRD writing is time-consuming, formats are inconsistent, and requirement descriptions are unclear",
      author: "pmoser · GitHub Skills推荐",
      likes: 82, views: "5.8K", comments: 10,
    },
    {
      title: "pm-roadmap：产品路线图规划",
      titleEn: "pm-roadmap: Product Roadmap Planning",
      role: "productManager",
      tags: ["产品经理", "路线图", "产品规划", "Claude Code", "AI技能"],
      tagsEn: ["Product Manager", "Roadmap", "Product Planning", "Claude Code", "AI Skill"],
      content: `## pm-roadmap 使用指南\n\n### 核心定位\n产品路线图规划skill，帮助产品经理制定清晰的产品演进路径。\n\n### 能力范围\n- 多版本路线图生成\n- 功能优先级排序\n- 资源分配建议\n- 风险点识别\n\n### 适用场景\n- 季度/年度产品规划\n- 向管理层汇报产品方向\n- 团队对齐产品目标\n\n### 追踪来源\nhttps://github.com/pmoser/pm-skills`,
      description: "产品路线图规划skill，制定清晰的产品演进路径和优先级排序",
      descriptionEn: "Product roadmap planning skill for creating clear product evolution paths and priority sorting",
      scenario: "产品经理需要制定季度或年度产品规划并向管理层汇报",
      scenarioEn: "Product managers needing to create quarterly or annual product plans and present to leadership",
      problemFocus: "产品方向不清晰，团队对产品目标缺乏共识",
      problemFocusEn: "Product direction is unclear, teams lack consensus on product goals",
      author: "pmoser · GitHub Skills推荐",
      likes: 68, views: "4.9K", comments: 8,
    },
    {
      title: "pm-jira：Jira看板与敏捷管理",
      titleEn: "pm-jira: Jira Board & Agile Management",
      role: "productManager",
      tags: ["产品经理", "Jira", "敏捷管理", "Claude Code", "AI技能"],
      tagsEn: ["Product Manager", "Jira", "Agile Management", "Claude Code", "AI Skill"],
      content: `## pm-jira 使用指南\n\n### 核心定位\nJira看板与敏捷管理skill，帮助产品经理高效管理开发进度。\n\n### 能力范围\n- Jira ticket自动创建和更新\n- 看板状态同步\n- Sprint规划辅助\n- 燃尽图分析\n\n### 适用场景\n- 敏捷开发团队的项目管理\n- Sprint规划和回顾\n- 开发进度跟踪\n\n### 追踪来源\nhttps://github.com/pmoser/pm-skills`,
      description: "Jira看板与敏捷管理skill，高效管理开发进度和Sprint规划",
      descriptionEn: "Jira board and agile management skill for efficiently managing development progress and sprint planning",
      scenario: "敏捷开发团队需要高效管理项目进度和Sprint",
      scenarioEn: "Agile development teams needing to efficiently manage project progress and sprints",
      problemFocus: "Jira操作繁琐，看板状态不同步，Sprint规划效率低",
      problemFocusEn: "Jira operations are cumbersome, board states are unsynchronized, sprint planning is inefficient",
      author: "pmoser · GitHub Skills推荐",
      likes: 71, views: "5.1K", comments: 9,
    },
    {
      title: "pm-personas：用户画像构建",
      titleEn: "pm-personas: User Persona Building",
      role: "productManager",
      tags: ["产品经理", "用户画像", "用户研究", "Claude Code", "AI技能"],
      tagsEn: ["Product Manager", "User Persona", "User Research", "Claude Code", "AI Skill"],
      content: `## pm-personas 使用指南\n\n### 核心定位\n用户画像构建skill，帮助产品经理基于数据构建精准的用户画像。\n\n### 能力范围\n- 用户画像模板生成\n- 用户行为分析\n- 需求场景梳理\n- 痛点识别\n\n### 适用场景\n- 新产品用户研究\n- 功能设计前的用户分析\n- 营销策略制定\n\n### 追踪来源\nhttps://github.com/pmoser/pm-skills`,
      description: "用户画像构建skill，基于数据构建精准的用户画像和需求场景",
      descriptionEn: "User persona building skill for creating accurate user personas and requirement scenarios based on data",
      scenario: "产品经理需要进行用户研究和画像构建",
      scenarioEn: "Product managers needing to conduct user research and build personas",
      problemFocus: "用户画像流于表面，缺乏数据支撑，需求场景不清晰",
      problemFocusEn: "User personas are superficial, lack data support, and requirement scenarios are unclear",
      author: "pmoser · GitHub Skills推荐",
      likes: 64, views: "4.6K", comments: 7,
    },
    {
      title: "pm-testing：产品测试策略",
      titleEn: "pm-testing: Product Testing Strategy",
      role: "productManager",
      tags: ["产品经理", "测试策略", "质量保障", "Claude Code", "AI技能"],
      tagsEn: ["Product Manager", "Testing Strategy", "Quality Assurance", "Claude Code", "AI Skill"],
      content: `## pm-testing 使用指南\n\n### 核心定位\n产品测试策略skill，帮助产品经理制定全面的测试计划和验收标准。\n\n### 能力范围\n- 测试用例生成\n- 验收标准制定\n- A/B测试方案设计\n- 用户验收测试(UAT)规划\n\n### 适用场景\n- 功能上线前的测试规划\n- 验收标准制定\n- 质量保障流程建立\n\n### 追踪来源\nhttps://github.com/pmoser/pm-skills`,
      description: "产品测试策略skill，制定全面的测试计划和验收标准",
      descriptionEn: "Product testing strategy skill for creating comprehensive test plans and acceptance criteria",
      scenario: "产品经理需要在功能上线前制定测试计划和验收标准",
      scenarioEn: "Product managers needing to create test plans and acceptance criteria before feature launch",
      problemFocus: "测试覆盖不全面，验收标准模糊，上线后Bug频发",
      problemFocusEn: "Test coverage is incomplete, acceptance criteria are vague, and bugs frequently appear after launch",
      author: "pmoser · GitHub Skills推荐",
      likes: 58, views: "4.1K", comments: 6,
    },
    {
      title: "pm-prototyping：快速原型制作",
      titleEn: "pm-prototyping: Rapid Prototyping",
      role: "productManager",
      tags: ["产品经理", "原型制作", "交互设计", "Claude Code", "AI技能"],
      tagsEn: ["Product Manager", "Prototyping", "Interaction Design", "Claude Code", "AI Skill"],
      content: `## pm-prototyping 使用指南\n\n### 核心定位\n快速原型制作skill，帮助产品经理快速将想法转化为可交互的原型。\n\n### 能力范围\n- 线框图生成\n- 交互流程设计\n- 高保真原型建议\n- 原型评审 checklist\n\n### 适用场景\n- 产品概念验证\n- 设计方案快速迭代\n- 与设计师和开发者的沟通\n\n### 追踪来源\nhttps://github.com/pmoser/pm-skills`,
      description: "快速原型制作skill，将产品想法快速转化为可交互的线框图和原型",
      descriptionEn: "Rapid prototyping skill for quickly turning product ideas into interactive wireframes and prototypes",
      scenario: "产品经理需要快速验证产品概念和迭代设计方案",
      scenarioEn: "Product managers needing to quickly validate product concepts and iterate design solutions",
      problemFocus: "原型制作工具学习成本高，概念验证周期长",
      problemEn: "Prototyping tools have high learning costs and concept validation cycles are long",
      author: "pmoser · GitHub Skills推荐",
      likes: 72, views: "5.3K", comments: 9,
    },
    {
      title: "pm-metrics：产品指标与分析",
      titleEn: "pm-metrics: Product Metrics & Analytics",
      role: "productManager",
      tags: ["产品经理", "数据分析", "产品指标", "Claude Code", "AI技能"],
      tagsEn: ["Product Manager", "Data Analysis", "Product Metrics", "Claude Code", "AI Skill"],
      content: `## pm-metrics 使用指南\n\n### 核心定位\n产品指标与分析skill，帮助产品经理建立科学的产品数据指标体系。\n\n### 能力范围\n- 核心指标定义（DAU/MAU/留存/转化率）\n- 漏斗分析\n- AARRR模型应用\n- 数据驱动决策框架\n\n### 适用场景\n- 产品数据体系搭建\n- 功能效果评估\n- 增长策略制定\n\n### 追踪来源\nhttps://github.com/pmoser/pm-skills`,
      description: "产品指标与分析skill，建立科学的数据指标体系和驱动决策框架",
      descriptionEn: "Product metrics and analytics skill for building scientific data indicator systems and driving decision frameworks",
      scenario: "产品经理需要建立数据指标体系并驱动产品决策",
      scenarioEn: "Product managers needing to build data indicator systems and drive product decisions",
      problemFocus: "缺乏科学的数据指标体系，产品决策靠感觉而非数据",
      problemFocusEn: "Lack of scientific data indicator systems, product decisions rely on intuition rather than data",
      author: "pmoser · GitHub Skills推荐",
      likes: 81, views: "5.7K", comments: 10,
    },

    // ===== 文章3: product-marketing-context =====
    {
      title: "product-marketing-context：产品营销上下文管理",
      titleEn: "product-marketing-context: Product Marketing Context Management",
      role: "productManager",
      tags: ["产品经理", "产品营销", "上下文管理", "Claude Code", "AI技能"],
      tagsEn: ["Product Manager", "Product Marketing", "Context Management", "Claude Code", "AI Skill"],
      content: `## product-marketing-context 使用指南\n\n### 核心定位\n解决每次让AI写方案都要重新介绍产品的痛点。通过一个配置文件保存产品核心信息，AI自动读取并应用于所有营销内容的生成。\n\n### 工作流程\n1. 创建产品核心信息配置文件（产品定位、目标用户、核心卖点、竞品差异等）\n2. Skill自动读取配置文件作为上下文\n3. 所有营销内容生成时自动引用产品信息\n4. 支持多产品配置切换\n\n### 核心价值\n- 告别每次重复介绍产品\n- 营销内容风格统一\n- 产品信息实时同步\n- 团队协作共享产品上下文\n\n### 追踪来源\nhttps://github.com/yourusername/product-marketing-context`,
      description: "产品营销上下文管理skill，保存产品核心信息告别每次重复介绍",
      descriptionEn: "Product marketing context management skill, saving core product info to eliminate repetitive introductions",
      scenario: "产品经理和营销人员每次让AI写方案都要重新介绍产品",
      scenarioEn: "Product managers and marketers having to reintroduce product every time they ask AI to write content",
      problemFocus: "每次AI写营销内容都要重新介绍产品，效率低下且风格不一致",
      problemFocusEn: "Having to reintroduce product every time AI writes marketing content, inefficient and inconsistent style",
      author: "product-marketing-context · 技能推荐",
      likes: 94, views: "6.8K", comments: 13,
    },

    // ===== 文章4: Google Stitch Skills 7个 =====
    {
      title: "stitch-generate-designs：AI设计稿生成",
      titleEn: "stitch-generate-designs: AI Design Generation",
      role: "creator",
      tags: ["设计系统", "AI设计", "Google Stitch", "Claude Code", "AI技能"],
      tagsEn: ["Design System", "AI Design", "Google Stitch", "Claude Code", "AI Skill"],
      content: `## stitch-generate-designs 使用指南\n\n### 核心定位\nGoogle Stitch官方skill，通过文字描述直接生成高保真UI设计稿。\n\n### 能力范围\n- 文字描述转UI设计稿\n- 多种设备尺寸适配（手机/平板/桌面）\n- 自动应用设计系统规范\n- 支持迭代修改\n\n### 安装\n\`\`\`bash\nnpx skills add google/stitch-skills@generate-designs -g -y\n\`\`\`\n\n### 追踪来源\nGitHub: https://github.com/google/stitch-skills`,
      description: "Google Stitch官方skill，文字描述直接生成高保真UI设计稿",
      descriptionEn: "Google Stitch official skill, generating high-fidelity UI designs from text descriptions",
      scenario: "设计师和开发者需要快速生成UI原型和设计稿",
      scenarioEn: "Designers and developers needing to quickly generate UI prototypes and design mockups",
      problemFocus: "设计稿制作耗时长，从概念到视觉稿流程繁琐",
      problemFocusEn: "Design mockup creation is time-consuming, the process from concept to visual is cumbersome",
      author: "Google · Stitch Skills",
      likes: 128, views: "9.5K", comments: 18,
    },
    {
      title: "stitch-generate-designs-from-image：图片转设计稿",
      titleEn: "stitch-generate-designs-from-image: Image to Design Conversion",
      role: "creator",
      tags: ["设计系统", "图片转设计", "Google Stitch", "Claude Code", "AI技能"],
      tagsEn: ["Design System", "Image to Design", "Google Stitch", "Claude Code", "AI Skill"],
      content: `## stitch-generate-designs-from-image 使用指南\n\n### 核心定位\nGoogle Stitch官方skill，将参考图片或草图转化为可编辑的UI设计稿。\n\n### 能力范围\n- 参考图片风格提取\n- 草图转高保真设计\n- 截图还原设计稿\n- 风格迁移和适配\n\n### 安装\n\`\`\`bash\nnpx skills add google/stitch-skills@generate-designs-from-image -g -y\n\`\`\`\n\n### 追踪来源\nGitHub: https://github.com/google/stitch-skills`,
      description: "Google Stitch官方skill，将参考图片或草图转化为可编辑的UI设计稿",
      descriptionEn: "Google Stitch official skill, converting reference images or sketches into editable UI designs",
      scenario: "设计师需要将草图或参考图快速转化为可编辑的设计稿",
      scenarioEn: "Designers needing to quickly convert sketches or reference images into editable designs",
      problemFocus: "从草图到高保真设计稿的转换过程耗时且需要专业技能",
      problemFocusEn: "Converting sketches to high-fidelity designs is time-consuming and requires professional skills",
      author: "Google · Stitch Skills",
      likes: 115, views: "8.2K", comments: 15,
    },
    {
      title: "stitch-update-design：设计稿迭代更新",
      titleEn: "stitch-update-design: Design Iteration & Update",
      role: "creator",
      tags: ["设计系统", "设计迭代", "Google Stitch", "Claude Code", "AI技能"],
      tagsEn: ["Design System", "Design Iteration", "Google Stitch", "Claude Code", "AI Skill"],
      content: `## stitch-update-design 使用指南\n\n### 核心定位\nGoogle Stitch官方skill，对已有设计稿进行迭代修改和版本更新。\n\n### 能力范围\n- 设计稿局部修改\n- 全局样式统一更新\n- 多版本对比\n- 变更历史追踪\n\n### 安装\n\`\`\`bash\nnpx skills add google/stitch-skills@update-design -g -y\n\`\`\`\n\n### 追踪来源\nGitHub: https://github.com/google/stitch-skills`,
      description: "Google Stitch官方skill，对已有设计稿进行迭代修改和版本管理",
      descriptionEn: "Google Stitch official skill for iterating and version-managing existing design mockups",
      scenario: "设计师需要对已有设计稿进行快速迭代和修改",
      scenarioEn: "Designers needing to quickly iterate and modify existing design mockups",
      problemFocus: "设计稿修改需要手动调整大量元素，迭代效率低",
      problemFocusEn: "Design modifications require manual adjustment of many elements, iteration is inefficient",
      author: "Google · Stitch Skills",
      likes: 98, views: "7.1K", comments: 12,
    },
    {
      title: "stitch-design-system-extraction：设计系统提取",
      titleEn: "stitch-design-system-extraction: Design System Extraction",
      role: "creator",
      tags: ["设计系统", "规范提取", "Google Stitch", "Claude Code", "AI技能"],
      tagsEn: ["Design System", "Spec Extraction", "Google Stitch", "Claude Code", "AI Skill"],
      content: `## stitch-design-system-extraction 使用指南\n\n### 核心定位\nGoogle Stitch官方skill，从设计稿中自动提取设计系统规范（颜色、字体、间距、组件等）。\n\n### 能力范围\n- 颜色板提取\n- 字体规范整理\n- 间距和布局规则\n- 组件库生成\n\n### 安装\n\`\`\`bash\nnpx skills add google/stitch-skills@design-system-extraction -g -y\n\`\`\`\n\n### 追踪来源\nGitHub: https://github.com/google/stitch-skills`,
      description: "Google Stitch官方skill，从设计稿自动提取颜色、字体、间距等设计系统规范",
      descriptionEn: "Google Stitch official skill, automatically extracting design system specs like colors, fonts, and spacing from mockups",
      scenario: "设计团队需要从现有设计稿中提取和整理设计系统规范",
      scenarioEn: "Design teams needing to extract and organize design system specs from existing mockups",
      problemFocus: "设计系统规范分散在多个设计稿中，手动提取耗时且容易遗漏",
      problemFocusEn: "Design system specs are scattered across multiple mockups, manual extraction is time-consuming and prone to omissions",
      author: "Google · Stitch Skills",
      likes: 106, views: "7.8K", comments: 14,
    },
    {
      title: "stitch-react-components：设计转React组件",
      titleEn: "stitch-react-components: Design to React Components",
      role: "developer",
      tags: ["前端开发", "React", "设计转代码", "Google Stitch", "AI技能"],
      tagsEn: ["Frontend", "React", "Design to Code", "Google Stitch", "AI Skill"],
      content: `## stitch-react-components 使用指南\n\n### 核心定位\nGoogle Stitch官方skill，将设计稿一键转换为可用的React组件代码。\n\n### 能力范围\n- 设计稿转React组件\n- CSS-in-JS样式生成\n- 组件props定义\n- 响应式适配\n\n### 安装\n\`\`\`bash\nnpx skills add google/stitch-skills@react-components -g -y\n\`\`\`\n\n### 追踪来源\nGitHub: https://github.com/google/stitch-skills`,
      description: "Google Stitch官方skill，将设计稿一键转换为可用的React组件代码",
      descriptionEn: "Google Stitch official skill, one-click converting design mockups to usable React component code",
      scenario: "前端开发者需要将设计稿快速转换为可复用的React组件",
      scenarioEn: "Frontend developers needing to quickly convert design mockups to reusable React components",
      problemFocus: "设计稿到代码的手动转换耗时且容易有像素偏差",
      problemFocusEn: "Manual conversion from design to code is time-consuming and prone to pixel deviations",
      author: "Google · Stitch Skills",
      likes: 142, views: "10.5K", comments: 21,
    },
    {
      title: "stitch-design-prototype-video：设计演示视频生成",
      titleEn: "stitch-design-prototype-video: Design Demo Video Generation",
      role: "creator",
      tags: ["设计系统", "演示视频", "Google Stitch", "Claude Code", "AI技能"],
      tagsEn: ["Design System", "Demo Video", "Google Stitch", "Claude Code", "AI Skill"],
      content: `## stitch-design-prototype-video 使用指南\n\n### 核心定位\nGoogle Stitch官方skill，将UI设计稿转化为可交互的演示视频。\n\n### 能力范围\n- 设计稿转交互演示\n- 点击流程录制\n- 动画效果生成\n- 视频导出\n\n### 安装\n\`\`\`bash\nnpx skills add google/stitch-skills@design-prototype-video -g -y\n\`\`\`\n\n### 追踪来源\nGitHub: https://github.com/google/stitch-skills`,
      description: "Google Stitch官方skill，将UI设计稿转化为可交互的演示视频",
      descriptionEn: "Google Stitch official skill, converting UI design mockups into interactive demo videos",
      scenario: "设计师和产品经理需要将设计稿转化为演示视频用于展示",
      scenarioEn: "Designers and PMs needing to convert design mockups into demo videos for presentation",
      problemFocus: "设计演示需要手动录制和剪辑，制作周期长",
      problemFocusEn: "Design demos require manual recording and editing, production cycle is long",
      author: "Google · Stitch Skills",
      likes: 89, views: "6.5K", comments: 11,
    },
    {
      title: "stitch-design：Google Stitch设计助手",
      titleEn: "stitch-design: Google Stitch Design Assistant",
      role: "creator",
      tags: ["设计系统", "AI设计助手", "Google Stitch", "Claude Code", "AI技能"],
      tagsEn: ["Design System", "AI Design Assistant", "Google Stitch", "Claude Code", "AI Skill"],
      content: `## stitch-design 使用指南\n\n### 核心定位\nGoogle Stitch核心设计助手skill，统筹管理所有设计相关的AI能力。\n\n### 能力范围\n- 设计系统管理\n- 组件库维护\n- 设计规范检查\n- 跨skill协调\n\n### 安装\n\`\`\`bash\nnpx skills add google/stitch-skills@design -g -y\n\`\`\`\n\n### 追踪来源\nGitHub: https://github.com/google/stitch-skills`,
      description: "Google Stitch核心设计助手skill，统筹管理设计系统和组件库",
      descriptionEn: "Google Stitch core design assistant skill, managing design systems and component libraries",
      scenario: "设计团队需要统一管理和维护设计系统",
      scenarioEn: "Design teams needing to uniformly manage and maintain design systems",
      problemFocus: "设计系统维护困难，组件库版本混乱",
      problemFocusEn: "Design system maintenance is difficult, component library versions are chaotic",
      author: "Google · Stitch Skills",
      likes: 118, views: "8.6K", comments: 16,
    },

    // ===== 文章5: markdown-viewer-skill =====
    {
      title: "markdown-viewer：Markdown代码块可视化",
      titleEn: "markdown-viewer: Markdown Code Block Visualization",
      role: "developer",
      tags: ["Markdown", "代码可视化", "文档渲染", "Claude Code", "AI技能"],
      tagsEn: ["Markdown", "Code Visualization", "Document Rendering", "Claude Code", "AI Skill"],
      content: `## markdown-viewer 使用指南\n\n### 核心定位\n让Markdown里的代码块活起来的skill。不只是语法高亮，而是让代码在文档中可视化运行和展示。\n\n### 能力范围\n- 代码块语法高亮增强\n- 实时代码预览\n- 图表和流程图渲染（Mermaid等）\n- 交互式代码演示\n\n### 适用场景\n- 技术文档编写\n- 代码教程制作\n- API文档展示\n- README美化\n\n### 追踪来源\nhttps://github.com/markdown-viewer/skills`,
      description: "让Markdown代码块活起来的skill，支持实时预览和交互式代码演示",
      descriptionEn: "Skill that brings Markdown code blocks to life, supporting real-time preview and interactive code demos",
      scenario: "技术文档编写和代码教程制作需要可视化展示代码效果",
      scenarioEn: "Technical documentation and code tutorials needing visual code effect display",
      problemFocus: "Markdown代码块只是静态文本，无法直观展示代码运行效果",
      problemFocusEn: "Markdown code blocks are just static text, unable to intuitively show code execution effects",
      author: "markdown-viewer · 每日Skills推荐",
      likes: 76, views: "5.4K", comments: 9,
    },

    // ===== 文章6: claude-task-master (Andrej Karpathy) =====
    {
      title: "claude-task-master：任务管理大师(Andrej Karpathy版)",
      titleEn: "claude-task-master: Task Management Master (Andrej Karpathy)",
      role: "developer",
      tags: ["Claude Code", "任务管理", "Andrej Karpathy", "AI技能"],
      tagsEn: ["Claude Code", "Task Management", "Andrej Karpathy", "AI Skill"],
      content: `## claude-task-master 使用指南\n\n### 核心定位\n由Tesla前AI总监Andrej Karpathy推荐的任务管理skill。将复杂项目拆解为可管理的任务列表，并与Claude Code深度集成。\n\n### 能力范围\n- 复杂项目任务拆解\n- 任务优先级自动排序\n- 依赖关系管理\n- 进度追踪和状态更新\n- 与Claude Code工作流集成\n\n### 核心特点\n- 支持多级任务嵌套\n- 自动生成任务描述和验收标准\n- 任务完成后自动归档\n- 支持团队协作和任务分配\n\n### 追踪来源\nAndrej Karpathy推荐\nhttps://github.com/eyaltoledano/claude-task-master`,
      description: "Andrej Karpathy推荐的任务管理skill，复杂项目拆解为可管理任务并与Claude Code深度集成",
      descriptionEn: "Andrej Karpathy-recommended task management skill, breaking complex projects into manageable tasks with deep Claude Code integration",
      scenario: "开发者需要管理复杂项目的大量任务和依赖关系",
      scenarioEn: "Developers needing to manage large numbers of tasks and dependencies in complex projects",
      problemFocus: "复杂项目任务管理混乱，优先级不清，进度难以追踪",
      problemFocusEn: "Complex project task management is chaotic, priorities are unclear, and progress is hard to track",
      author: "eyaltoledano · Andrej Karpathy推荐",
      likes: 156, views: "12.3K", comments: 24,
    },

    // ===== 文章7: planning-with-files =====
    {
      title: "planning-with-files：基于文件的智能规划",
      titleEn: "planning-with-files: File-Based Intelligent Planning",
      role: "developer",
      tags: ["Claude Code", "文件管理", "智能规划", "AI技能"],
      tagsEn: ["Claude Code", "File Management", "Intelligent Planning", "AI Skill"],
      content: `## planning-with-files 使用指南\n\n### 核心定位\n基于项目文件自动生成开发规划的skill。AI通过分析代码库结构和内容，智能生成开发计划和任务列表。\n\n### 能力范围\n- 代码库结构分析\n- 自动任务生成\n- 开发计划制定\n- 文件依赖关系梳理\n- 代码复杂度评估\n\n### 工作流程\n1. AI分析项目文件结构和代码内容\n2. 自动生成开发任务列表\n3. 按优先级和依赖关系排序\n4. 生成可执行的开发计划\n\n### 追踪来源\nhttps://github.com/anthropics/skills/tree/main/planning-with-files`,
      description: "基于项目文件自动生成开发规划的skill，分析代码库结构和内容智能生成任务列表",
      descriptionEn: "File-based intelligent planning skill that analyzes codebase structure and content to auto-generate task lists",
      scenario: "开发者接手新项目时需要快速理解项目结构并制定开发计划",
      scenarioEn: "Developers taking over new projects needing to quickly understand structure and create development plans",
      problemFocus: "接手新项目时理解成本高，开发计划制定耗时长",
      problemFocusEn: "High understanding cost when taking over new projects, development plan creation is time-consuming",
      author: "anthropics · GitHub Skills推荐",
      likes: 92, views: "6.8K", comments: 13,
    },

    // ===== 文章8: Andrej Karpathy Skills (8个代表性skill) =====
    {
      title: "claude-code-terminal：终端开发增强",
      titleEn: "claude-code-terminal: Terminal Development Enhancement",
      role: "developer",
      tags: ["Claude Code", "终端开发", "命令行", "AI技能"],
      tagsEn: ["Claude Code", "Terminal Development", "CLI", "AI Skill"],
      content: `## claude-code-terminal 使用指南\n\n### 核心定位\n增强Claude Code在终端环境中的开发能力，支持复杂的命令行操作和脚本编写。\n\n### 能力范围\n- Shell脚本生成和调试\n- 命令行工具开发\n- 终端工作流自动化\n- 系统管理任务\n\n### 追踪来源\nAndrej Karpathy技能合集`,
      description: "增强Claude Code终端开发能力的skill，支持复杂命令行操作和脚本编写",
      descriptionEn: "Skill enhancing Claude Code terminal development capabilities, supporting complex CLI operations and scripting",
      scenario: "开发者需要在终端环境中进行复杂的命令行开发和自动化",
      scenarioEn: "Developers needing to perform complex CLI development and automation in terminal environments",
      problemFocus: "终端开发效率低，脚本编写容易出错",
      problemFocusEn: "Terminal development is inefficient, scripting is error-prone",
      author: "Andrej Karpathy Skills合集",
      likes: 87, views: "6.5K", comments: 11,
    },
    {
      title: "claude-code-browser：浏览器自动化",
      titleEn: "claude-code-browser: Browser Automation",
      role: "developer",
      tags: ["Claude Code", "浏览器自动化", "Web爬虫", "AI技能"],
      tagsEn: ["Claude Code", "Browser Automation", "Web Scraping", "AI Skill"],
      content: `## claude-code-browser 使用指南\n\n### 核心定位\n让Claude Code能够控制浏览器进行自动化操作的skill，支持Web测试、数据抓取和网页交互。\n\n### 能力范围\n- 浏览器自动化控制\n- Web应用测试\n- 数据抓取和采集\n- 网页内容分析\n\n### 追踪来源\nAndrej Karpathy技能合集`,
      description: "让Claude Code控制浏览器进行自动化操作的skill，支持Web测试和数据抓取",
      descriptionEn: "Skill letting Claude Code control browsers for automation, supporting web testing and data scraping",
      scenario: "开发者需要进行Web自动化测试和数据抓取",
      scenarioEn: "Developers needing to perform web automated testing and data scraping",
      problemFocus: "浏览器自动化配置复杂，维护成本高",
      problemFocusEn: "Browser automation configuration is complex, maintenance cost is high",
      author: "Andrej Karpathy Skills合集",
      likes: 94, views: "7.1K", comments: 13,
    },
    {
      title: "claude-code-database：数据库操作助手",
      titleEn: "claude-code-database: Database Operation Assistant",
      role: "developer",
      tags: ["Claude Code", "数据库", "SQL", "AI技能"],
      tagsEn: ["Claude Code", "Database", "SQL", "AI Skill"],
      content: `## claude-code-database 使用指南\n\n### 核心定位\n数据库操作增强skill，让Claude Code能够理解和操作各种数据库。\n\n### 能力范围\n- SQL查询生成和优化\n- 数据库Schema分析\n- 数据迁移脚本生成\n- 性能瓶颈诊断\n\n### 追踪来源\nAndrej Karpathy技能合集`,
      description: "数据库操作增强skill，支持SQL生成优化和Schema分析",
      descriptionEn: "Database operation enhancement skill, supporting SQL generation/optimization and schema analysis",
      scenario: "开发者需要与数据库交互进行查询和优化",
      scenarioEn: "Developers needing to interact with databases for queries and optimization",
      problemFocus: "SQL编写效率低，数据库优化缺乏经验",
      problemFocusEn: "SQL writing is inefficient, database optimization lacks experience",
      author: "Andrej Karpathy Skills合集",
      likes: 78, views: "5.8K", comments: 10,
    },
    {
      title: "claude-code-debug：调试专家",
      titleEn: "claude-code-debug: Debugging Expert",
      role: "developer",
      tags: ["Claude Code", "调试", "Bug修复", "AI技能"],
      tagsEn: ["Claude Code", "Debugging", "Bug Fix", "AI Skill"],
      content: `## claude-code-debug 使用指南\n\n### 核心定位\n调试专家skill，帮助开发者快速定位和修复代码中的Bug。\n\n### 能力范围\n- 错误日志分析\n- 断点调试辅助\n- 根本原因分析\n- 修复方案推荐\n\n### 追踪来源\nAndrej Karpathy技能合集`,
      description: "调试专家skill，快速定位和分析代码Bug的根本原因",
      descriptionEn: "Debugging expert skill for quickly locating and analyzing root causes of code bugs",
      scenario: "开发者需要快速定位和修复代码中的Bug",
      scenarioEn: "Developers needing to quickly locate and fix bugs in code",
      problemFocus: "Bug定位耗时长，调试过程缺乏系统性方法",
      problemFocusEn: "Bug localization is time-consuming, debugging lacks systematic methodology",
      author: "Andrej Karpathy Skills合集",
      likes: 102, views: "7.8K", comments: 15,
    },
    {
      title: "claude-code-deploy：部署自动化",
      titleEn: "claude-code-deploy: Deployment Automation",
      role: "developer",
      tags: ["Claude Code", "部署", "DevOps", "CI/CD", "AI技能"],
      tagsEn: ["Claude Code", "Deployment", "DevOps", "CI/CD", "AI Skill"],
      content: `## claude-code-deploy 使用指南\n\n### 核心定位\n部署自动化skill，帮助开发者一键完成应用部署和CI/CD流程配置。\n\n### 能力范围\n- 部署脚本生成\n- CI/CD流程配置\n- 容器化配置\n- 环境管理\n\n### 追踪来源\nAndrej Karpathy技能合集`,
      description: "部署自动化skill，一键完成应用部署和CI/CD流程配置",
      descriptionEn: "Deployment automation skill for one-click application deployment and CI/CD pipeline configuration",
      scenario: "开发者需要自动化部署流程和CI/CD配置",
      scenarioEn: "Developers needing to automate deployment processes and CI/CD configuration",
      problemFocus: "部署流程手动操作多，容易出错，配置复杂",
      problemFocusEn: "Deployment processes have many manual steps, are error-prone, and configuration is complex",
      author: "Andrej Karpathy Skills合集",
      likes: 85, views: "6.2K", comments: 11,
    },

    // ===== 文章9: 全岗位合集 (10个代表性skill) =====
    {
      title: "hr-recruitment：AI招聘助手",
      titleEn: "hr-recruitment: AI Recruitment Assistant",
      role: "operations",
      tags: ["HR", "招聘", "人才筛选", "Claude Code", "AI技能"],
      tagsEn: ["HR", "Recruitment", "Talent Screening", "Claude Code", "AI Skill"],
      content: `## hr-recruitment 使用指南\n\n### 核心定位\nAI招聘助手skill，帮助HR高效筛选简历和进行人才评估。\n\n### 能力范围\n- 简历智能筛选\n- 候选人匹配度评分\n- 面试问题生成\n- 招聘数据分析\n\n### 适用场景\n- 大批量简历筛选\n- 岗位需求分析\n- 面试流程优化\n\n### 追踪来源\nGitHub全岗位Skill合集`,
      description: "AI招聘助手skill，智能筛选简历和生成面试问题",
      descriptionEn: "AI recruitment assistant skill for intelligent resume screening and interview question generation",
      scenario: "HR需要高效筛选大量简历和优化面试流程",
      scenarioEn: "HR needing to efficiently screen large volumes of resumes and optimize interview processes",
      problemFocus: "简历筛选耗时，面试问题设计缺乏针对性",
      problemFocusEn: "Resume screening is time-consuming, interview questions lack specificity",
      author: "全岗位Skill合集",
      likes: 68, views: "4.8K", comments: 8,
    },
    {
      title: "legal-contract：合同审查助手",
      titleEn: "legal-contract: Contract Review Assistant",
      role: "operations",
      tags: ["法务", "合同审查", "合规", "Claude Code", "AI技能"],
      tagsEn: ["Legal", "Contract Review", "Compliance", "Claude Code", "AI Skill"],
      content: `## legal-contract 使用指南\n\n### 核心定位\n合同审查助手skill，帮助法务人员快速审查合同条款和识别风险点。\n\n### 能力范围\n- 合同条款自动审查\n- 风险点识别和标注\n- 合规性检查\n- 修改建议生成\n\n### 适用场景\n- 商务合同审查\n- 劳动合同审核\n- 供应商协议检查\n\n### 追踪来源\nGitHub全岗位Skill合集`,
      description: "合同审查助手skill，自动审查条款和识别风险点",
      descriptionEn: "Contract review assistant skill for automatic clause review and risk point identification",
      scenario: "法务人员需要高效审查大量合同",
      scenarioEn: "Legal professionals needing to efficiently review large volumes of contracts",
      problemFocus: "合同审查耗时长，容易遗漏关键风险条款",
      problemFocusEn: "Contract review is time-consuming, key risk clauses are easily missed",
      author: "全岗位Skill合集",
      likes: 72, views: "5.1K", comments: 9,
    },
    {
      title: "customer-service：客服智能助手",
      titleEn: "customer-service: Customer Service AI Assistant",
      role: "operations",
      tags: ["客服", "智能客服", "客户支持", "Claude Code", "AI技能"],
      tagsEn: ["Customer Service", "AI Support", "Customer Support", "Claude Code", "AI Skill"],
      content: `## customer-service 使用指南\n\n### 核心定位\n客服智能助手skill，帮助客服团队高效处理客户咨询和投诉。\n\n### 能力范围\n- 客户问题自动分类\n- 回复模板生成\n- 情绪识别和安抚\n- 工单自动分配\n\n### 适用场景\n- 在线客服支持\n- 投诉处理\n- 售后服务\n\n### 追踪来源\nGitHub全岗位Skill合集`,
      description: "客服智能助手skill，自动分类问题并生成回复模板",
      descriptionEn: "Customer service AI assistant skill for automatic issue classification and reply template generation",
      scenario: "客服团队需要高效处理大量客户咨询",
      scenarioEn: "Customer service teams needing to efficiently handle large volumes of inquiries",
      problemFocus: "客服回复效率低，投诉处理缺乏标准化流程",
      problemFocusEn: "Customer service reply efficiency is low, complaint handling lacks standardized processes",
      author: "全岗位Skill合集",
      likes: 64, views: "4.5K", comments: 7,
    },
    {
      title: "data-analyst：数据分析助手",
      titleEn: "data-analyst: Data Analysis Assistant",
      role: "dataScientist",
      tags: ["数据分析", "报表生成", "可视化", "Claude Code", "AI技能"],
      tagsEn: ["Data Analysis", "Report Generation", "Visualization", "Claude Code", "AI Skill"],
      content: `## data-analyst 使用指南\n\n### 核心定位\n数据分析助手skill，帮助数据分析师快速完成数据清洗、分析和报表生成。\n\n### 能力范围\n- 数据清洗和预处理\n- 统计分析\n- 可视化图表生成\n- 报表自动输出\n\n### 适用场景\n- 业务数据分析\n- 运营报表制作\n- 数据洞察发现\n\n### 追踪来源\nGitHub全岗位Skill合集`,
      description: "数据分析助手skill，快速完成数据清洗、分析和报表生成",
      descriptionEn: "Data analysis assistant skill for quickly completing data cleaning, analysis, and report generation",
      scenario: "数据分析师需要快速处理数据和生成报表",
      scenarioEn: "Data analysts needing to quickly process data and generate reports",
      problemFocus: "数据处理流程重复，报表制作耗时长",
      problemFocusEn: "Data processing workflows are repetitive, report creation is time-consuming",
      author: "全岗位Skill合集",
      likes: 81, views: "5.9K", comments: 10,
    },
    {
      title: "content-marketing：内容营销助手",
      titleEn: "content-marketing: Content Marketing Assistant",
      role: "growth",
      tags: ["内容营销", "社媒运营", "文案生成", "Claude Code", "AI技能"],
      tagsEn: ["Content Marketing", "Social Media", "Copywriting", "Claude Code", "AI Skill"],
      content: `## content-marketing 使用指南\n\n### 核心定位\n内容营销助手skill，帮助营销团队高效产出社交媒体内容和营销文案。\n\n### 能力范围\n- 社媒文案生成\n- 营销方案策划\n- 内容日历规划\n- 效果分析\n\n### 适用场景\n- 社交媒体运营\n- 品牌营销\n- 内容策划\n\n### 追踪来源\nGitHub全岗位Skill合集`,
      description: "内容营销助手skill，高效产出社媒文案和营销方案",
      descriptionEn: "Content marketing assistant skill for efficiently producing social media copy and marketing plans",
      scenario: "营销团队需要高效产出大量社媒内容和文案",
      scenarioEn: "Marketing teams needing to efficiently produce large volumes of social media content and copy",
      problemFocus: "内容创作耗时长，营销方案缺乏创意",
      problemFocusEn: "Content creation is time-consuming, marketing plans lack creativity",
      author: "全岗位Skill合集",
      likes: 76, views: "5.3K", comments: 9,
    },
  ];

  console.log(`Inserting ${newSkills.length} skills from 13 WeChat articles...`);
  for (const s of newSkills) {
    await db.insert(skills).values(s);
  }
  console.log("Batch 3 import complete!");

  // Verify counts
  const { count } = await import("drizzle-orm");
  const sCount = await db.select({ count: count() }).from(skills);
  console.log(`Total skills in database: ${sCount[0].count}`);

  process.exit(0);
}

importBatch3().catch(console.error);
