import { getDb } from "../api/queries/connection";
import { skills } from "../db/schema";

async function importBatch() {
  const db = getDb();

  const batch = [
    {
      title: "context-engineering: Context Engineering Precision Control",
      titleEn: "context-engineering: Context Engineering Precision Control",
      role: "developer",
      tags: ["Claude Code", "Context Engineering", "Prompt Engineering", "AI Skill"],
      tagsEn: ["Claude Code", "Context Engineering", "Prompt Engineering", "AI Skill"],
      content: "Context Engineering is the evolution of Prompt Engineering. It systematically manages all context information AI receives, making output predictable rather than luck-dependent. When AI output is uncontrollable, the issue is not poor prompts but overly casual context provision. Context Engineering uses structured, layered context management to ensure AI precisely understands intent every time.\n\nApplicable scenarios:\n- Complex project development requiring AI to continuously understand architecture\n- Multi-turn conversation coherence\n- Precise positioning of key content in large amounts of information\n- Unified AI working mode in team collaboration\n\nSource: https://mp.weixin.qq.com/s/On69fuwyaa-KXauEjkcAjg",
      description: "Context Engineering skill for systematically managing all context AI receives",
      descriptionEn: "Context Engineering skill for systematically managing all context AI receives",
      scenario: "Complex project development requiring AI to maintain context coherence",
      scenarioEn: "Complex project development requiring AI to maintain context coherence",
      problemFocus: "AI output uncontrollable due to overly casual context provision",
      problemFocusEn: "AI output uncontrollable due to overly casual context provision",
      author: "GitHub Selected Skills",
      likes: 89, views: "6.5K", comments: 12,
    },
    {
      title: "pm-planning: Product Planning & Feature Breakdown",
      titleEn: "pm-planning: Product Planning & Feature Breakdown",
      role: "productManager",
      tags: ["Product Manager", "Product Planning", "Feature Breakdown", "Claude Code", "AI Skill"],
      tagsEn: ["Product Manager", "Product Planning", "Feature Breakdown", "Claude Code", "AI Skill"],
      content: "Product planning and feature breakdown skill that transforms vague requirements into clear development plans. Capabilities include: requirement analysis and priority sorting, feature module breakdown and dependency mapping, development effort estimation, and milestone planning.\n\nSource: https://github.com/pmoser/pm-skills",
      description: "Product planning skill transforming vague requirements into clear development plans",
      descriptionEn: "Product planning skill transforming vague requirements into clear development plans",
      scenario: "Product managers planning new products or organizing version iterations",
      scenarioEn: "Product managers planning new products or organizing version iterations",
      problemFocus: "Vague requirements lead to unclear development plans",
      problemFocusEn: "Vague requirements lead to unclear development plans",
      author: "pmoser · GitHub Skills",
      likes: 76, views: "5.2K", comments: 9,
    },
    {
      title: "pm-prd: PRD Document Generation & Review",
      titleEn: "pm-prd: PRD Document Generation & Review",
      role: "productManager",
      tags: ["Product Manager", "PRD", "Requirements Doc", "Claude Code", "AI Skill"],
      tagsEn: ["Product Manager", "PRD", "Requirements Doc", "Claude Code", "AI Skill"],
      content: "PRD generation and review skill for quickly producing high-quality product requirement documents. Capabilities include: automatic PRD structure generation, requirement description standardization, acceptance criteria definition, and interaction flow diagram suggestions.\n\nSource: https://github.com/pmoser/pm-skills",
      description: "PRD document generation and review skill",
      descriptionEn: "PRD document generation and review skill",
      scenario: "Product managers needing standardized PRD documents",
      scenarioEn: "Product managers needing standardized PRD documents",
      problemFocus: "PRD writing is time-consuming with inconsistent formats",
      problemFocusEn: "PRD writing is time-consuming with inconsistent formats",
      author: "pmoser · GitHub Skills",
      likes: 82, views: "5.8K", comments: 10,
    },
    {
      title: "pm-roadmap: Product Roadmap Planning",
      titleEn: "pm-roadmap: Product Roadmap Planning",
      role: "productManager",
      tags: ["Product Manager", "Roadmap", "Product Planning", "Claude Code", "AI Skill"],
      tagsEn: ["Product Manager", "Roadmap", "Product Planning", "Claude Code", "AI Skill"],
      content: "Product roadmap planning skill for creating clear product evolution paths. Capabilities include: multi-version roadmap generation, feature priority sorting, resource allocation suggestions, and risk point identification.\n\nSource: https://github.com/pmoser/pm-skills",
      description: "Product roadmap planning with priority sorting",
      descriptionEn: "Product roadmap planning with priority sorting",
      scenario: "Product managers creating quarterly or annual plans",
      scenarioEn: "Product managers creating quarterly or annual plans",
      problemFocus: "Unclear product direction and lack of team consensus",
      problemFocusEn: "Unclear product direction and lack of team consensus",
      author: "pmoser · GitHub Skills",
      likes: 68, views: "4.9K", comments: 8,
    },
    {
      title: "pm-jira: Jira Board & Agile Management",
      titleEn: "pm-jira: Jira Board & Agile Management",
      role: "productManager",
      tags: ["Product Manager", "Jira", "Agile", "Claude Code", "AI Skill"],
      tagsEn: ["Product Manager", "Jira", "Agile", "Claude Code", "AI Skill"],
      content: "Jira board and agile management skill for efficiently managing development progress. Capabilities include: Jira ticket auto-creation and updates, board status synchronization, sprint planning assistance, and burndown chart analysis.\n\nSource: https://github.com/pmoser/pm-skills",
      description: "Jira and agile management for development progress",
      descriptionEn: "Jira and agile management for development progress",
      scenario: "Agile teams managing project progress and sprints",
      scenarioEn: "Agile teams managing project progress and sprints",
      problemFocus: "Jira operations are cumbersome and sprint planning is inefficient",
      problemFocusEn: "Jira operations are cumbersome and sprint planning is inefficient",
      author: "pmoser · GitHub Skills",
      likes: 71, views: "5.1K", comments: 9,
    },
    {
      title: "pm-personas: User Persona Building",
      titleEn: "pm-personas: User Persona Building",
      role: "productManager",
      tags: ["Product Manager", "User Persona", "User Research", "Claude Code", "AI Skill"],
      tagsEn: ["Product Manager", "User Persona", "User Research", "Claude Code", "AI Skill"],
      content: "User persona building skill for creating accurate user personas based on data. Capabilities include: persona template generation, user behavior analysis, requirement scenario mapping, and pain point identification.\n\nSource: https://github.com/pmoser/pm-skills",
      description: "User persona building with data-driven scenarios",
      descriptionEn: "User persona building with data-driven scenarios",
      scenario: "Product managers conducting user research",
      scenarioEn: "Product managers conducting user research",
      problemFocus: "User personas are superficial and lack data support",
      problemFocusEn: "User personas are superficial and lack data support",
      author: "pmoser · GitHub Skills",
      likes: 64, views: "4.6K", comments: 7,
    },
    {
      title: "pm-testing: Product Testing Strategy",
      titleEn: "pm-testing: Product Testing Strategy",
      role: "productManager",
      tags: ["Product Manager", "Testing", "QA", "Claude Code", "AI Skill"],
      tagsEn: ["Product Manager", "Testing", "QA", "Claude Code", "AI Skill"],
      content: "Product testing strategy skill for comprehensive test plans and acceptance criteria. Capabilities include: test case generation, acceptance criteria definition, A/B test design, and UAT planning.\n\nSource: https://github.com/pmoser/pm-skills",
      description: "Product testing strategy and acceptance criteria",
      descriptionEn: "Product testing strategy and acceptance criteria",
      scenario: "Product managers creating test plans before launch",
      scenarioEn: "Product managers creating test plans before launch",
      problemFocus: "Incomplete test coverage and vague acceptance criteria",
      problemFocusEn: "Incomplete test coverage and vague acceptance criteria",
      author: "pmoser · GitHub Skills",
      likes: 58, views: "4.1K", comments: 6,
    },
    {
      title: "pm-prototyping: Rapid Prototyping",
      titleEn: "pm-prototyping: Rapid Prototyping",
      role: "productManager",
      tags: ["Product Manager", "Prototyping", "Design", "Claude Code", "AI Skill"],
      tagsEn: ["Product Manager", "Prototyping", "Design", "Claude Code", "AI Skill"],
      content: "Rapid prototyping skill for quickly turning product ideas into interactive wireframes. Capabilities include: wireframe generation, interaction flow design, high-fidelity prototype suggestions, and prototype review checklists.\n\nSource: https://github.com/pmoser/pm-skills",
      description: "Rapid prototyping for interactive wireframes",
      descriptionEn: "Rapid prototyping for interactive wireframes",
      scenario: "Product managers validating product concepts",
      scenarioEn: "Product managers validating product concepts",
      problemFocus: "High learning cost of prototyping tools and long validation cycles",
      problemFocusEn: "High learning cost of prototyping tools and long validation cycles",
      author: "pmoser · GitHub Skills",
      likes: 72, views: "5.3K", comments: 9,
    },
    {
      title: "pm-metrics: Product Metrics & Analytics",
      titleEn: "pm-metrics: Product Metrics & Analytics",
      role: "productManager",
      tags: ["Product Manager", "Metrics", "Analytics", "Claude Code", "AI Skill"],
      tagsEn: ["Product Manager", "Metrics", "Analytics", "Claude Code", "AI Skill"],
      content: "Product metrics and analytics skill for building scientific data indicator systems. Capabilities include: core metrics definition (DAU/MAU/retention/conversion), funnel analysis, AARRR model application, and data-driven decision frameworks.\n\nSource: https://github.com/pmoser/pm-skills",
      description: "Product metrics and data-driven decision frameworks",
      descriptionEn: "Product metrics and data-driven decision frameworks",
      scenario: "Product managers building data indicator systems",
      scenarioEn: "Product managers building data indicator systems",
      problemFocus: "Lack of scientific data indicators, decisions rely on intuition",
      problemFocusEn: "Lack of scientific data indicators, decisions rely on intuition",
      author: "pmoser · GitHub Skills",
      likes: 81, views: "5.7K", comments: 10,
    },
    {
      title: "product-marketing-context: Product Marketing Context",
      titleEn: "product-marketing-context: Product Marketing Context",
      role: "productManager",
      tags: ["Product Manager", "Marketing", "Context", "Claude Code", "AI Skill"],
      tagsEn: ["Product Manager", "Marketing", "Context", "Claude Code", "AI Skill"],
      content: "Product marketing context management skill. Solves the pain of reintroducing product every time you ask AI to write content. Uses a config file to save core product info that AI automatically reads and applies to all marketing content generation. Supports multi-product config switching.\n\nSource: https://github.com/yourusername/product-marketing-context",
      description: "Product marketing context management eliminating repetitive introductions",
      descriptionEn: "Product marketing context management eliminating repetitive introductions",
      scenario: "PMs and marketers tired of reintroducing product to AI",
      scenarioEn: "PMs and marketers tired of reintroducing product to AI",
      problemFocus: "Reintroducing product every time is inefficient and inconsistent",
      problemFocusEn: "Reintroducing product every time is inefficient and inconsistent",
      author: "product-marketing-context",
      likes: 94, views: "6.8K", comments: 13,
    },
  ];

  for (const s of batch) {
    await db.insert(skills).values(s);
  }
  console.log(`Inserted ${batch.length} skills (batch 3a)`);
  process.exit(0);
}

importBatch().catch(console.error);
